DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='cuki_runtime') THEN CREATE ROLE cuki_runtime NOLOGIN NOBYPASSRLS; END IF; END $$;
CREATE OR REPLACE FUNCTION cuki_actor() RETURNS text LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.actor', true),'') $$;
CREATE OR REPLACE FUNCTION cuki_staff() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT coalesce(current_setting('app.role', true) IN ('admin','moderator'),false) $$;
CREATE TABLE entities (actor_id text NOT NULL, entity_type text NOT NULL, id text NOT NULL, version int NOT NULL CHECK(version>0), deleted boolean NOT NULL DEFAULT false, payload jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(actor_id,entity_type,id));
CREATE TABLE entity_history (actor_id text NOT NULL, entity_type text NOT NULL, id text NOT NULL, version int NOT NULL, deleted boolean NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(actor_id,entity_type,id,version));
CREATE TABLE changes (cursor bigserial PRIMARY KEY, actor_id text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, version int NOT NULL, deleted boolean NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX changes_actor_cursor ON changes(actor_id,cursor);
CREATE TABLE op_receipts(actor_id text NOT NULL,id text NOT NULL,digest text NOT NULL,response jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(actor_id,id));
CREATE TABLE challenges(id text PRIMARY KEY,actor_id text NOT NULL,version int NOT NULL DEFAULT 1,state text NOT NULL CHECK(state IN ('active','interrupted','ready_to_harvest','harvested','archived')),timezone text NOT NULL,policy_version text NOT NULL,boundaries jsonb NOT NULL CHECK(jsonb_array_length(boundaries)=53),seed bigint NOT NULL CHECK(seed BETWEEN 0 AND 4294967295),created_at timestamptz NOT NULL,archived_at timestamptz);
CREATE UNIQUE INDEX one_active_challenge ON challenges(actor_id) WHERE state IN ('active','ready_to_harvest');
CREATE TABLE garden_credits(challenge_id text NOT NULL REFERENCES challenges(id),actor_id text NOT NULL,week_index int NOT NULL CHECK(week_index BETWEEN 0 AND 51),session_id text NOT NULL,received_at timestamptz NOT NULL,PRIMARY KEY(challenge_id,week_index),UNIQUE(actor_id,session_id));
CREATE TABLE plants(id text PRIMARY KEY,actor_id text NOT NULL,challenge_id text NOT NULL UNIQUE REFERENCES challenges(id),descriptor jsonb NOT NULL,archived_at timestamptz NOT NULL);
CREATE TABLE coins(id text PRIMARY KEY,actor_id text NOT NULL,challenge_id text NOT NULL UNIQUE REFERENCES challenges(id),state text NOT NULL CHECK(state IN ('available','reserved','redeemed')),earned_at timestamptz NOT NULL);
CREATE TABLE reward_quotes(id text PRIMARY KEY,actor_id text NOT NULL,coin_id text NOT NULL REFERENCES coins(id),payload jsonb NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE redemptions(id text PRIMARY KEY,actor_id text NOT NULL,coin_id text NOT NULL REFERENCES coins(id),quote_id text NOT NULL REFERENCES reward_quotes(id),state text NOT NULL,provider_reference text UNIQUE,payload jsonb NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE UNIQUE INDEX one_live_redemption ON redemptions(coin_id) WHERE state NOT IN ('failed_released');
CREATE TABLE billing(actor_id text PRIMARY KEY,plan text NOT NULL DEFAULT 'free',state text NOT NULL DEFAULT 'active',store text,starts_at timestamptz,expires_at timestamptz,verified_at timestamptz NOT NULL,event_at timestamptz NOT NULL,payload jsonb NOT NULL DEFAULT '{}');
CREATE TABLE webhook_events(id text PRIMARY KEY,kind text NOT NULL,digest text NOT NULL,received_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE quota(actor_id text NOT NULL,period text NOT NULL,kind text NOT NULL CHECK(kind IN ('capture','action')),used int NOT NULL DEFAULT 0 CHECK(used>=0),reserved int NOT NULL DEFAULT 0 CHECK(reserved>=0),PRIMARY KEY(actor_id,period,kind));
CREATE TABLE jobs(id text PRIMARY KEY,actor_id text NOT NULL,route text NOT NULL,state text NOT NULL,media_id text,input text NOT NULL,ingredients jsonb NOT NULL DEFAULT '[]',result jsonb,error text,period text NOT NULL,quota_kind text NOT NULL,quota_state text NOT NULL CHECK(quota_state IN ('reserved','used','refunded')),attempts int NOT NULL DEFAULT 0,lease_until timestamptz,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX job_queue ON jobs(state,created_at);
CREATE TABLE proposals(id text PRIMARY KEY,actor_id text NOT NULL,version int NOT NULL,state text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE reports(id text PRIMARY KEY,actor_id text NOT NULL,target_type text NOT NULL,target_id text NOT NULL,reason text NOT NULL,details text NOT NULL,state text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL);
CREATE TABLE moderation(id text PRIMARY KEY,actor_id text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,version int NOT NULL,state text NOT NULL DEFAULT 'pending',reason text NOT NULL DEFAULT '',created_at timestamptz NOT NULL,UNIQUE(actor_id,entity_type,entity_id,version));
CREATE TABLE audit(id bigserial PRIMARY KEY,actor_id text NOT NULL,staff_id text,target_id text NOT NULL,action text NOT NULL,detail jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL);
CREATE TABLE media(id text PRIMARY KEY,actor_id text NOT NULL,purpose text NOT NULL,mime text NOT NULL,expected_bytes int NOT NULL CHECK(expected_bytes>0),state text NOT NULL,digest text,created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE privacy_jobs(id text PRIMARY KEY,actor_id text NOT NULL,kind text NOT NULL,state text NOT NULL,result jsonb,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE local_users(id text PRIMARY KEY,email text UNIQUE NOT NULL,password_hash text,verified boolean NOT NULL DEFAULT false,role text NOT NULL DEFAULT 'user',created_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE TABLE local_sessions(id text PRIMARY KEY,actor_id text NOT NULL REFERENCES local_users(id),token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz);
CREATE TABLE local_mail(id text PRIMARY KEY,actor_id text NOT NULL REFERENCES local_users(id),token_hash text NOT NULL,purpose text NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz,attempts int NOT NULL DEFAULT 0);
DO $$ DECLARE tab text; BEGIN
FOREACH tab IN ARRAY ARRAY['entities','entity_history','changes','op_receipts','challenges','garden_credits','plants','coins','reward_quotes','redemptions','billing','quota','jobs','proposals','reports','moderation','audit','media','privacy_jobs'] LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',tab);
 EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',tab);
 EXECUTE format('CREATE POLICY owner_read ON %I FOR SELECT TO cuki_runtime USING (actor_id=cuki_actor() OR cuki_staff())',tab);
 EXECUTE format('CREATE POLICY owner_write ON %I FOR ALL TO cuki_runtime USING (actor_id=cuki_actor() OR cuki_staff()) WITH CHECK (actor_id=cuki_actor() OR cuki_staff())',tab);
 EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO cuki_runtime',tab);
END LOOP; END $$;
CREATE POLICY public_entities ON entities FOR SELECT TO cuki_runtime USING (NOT deleted AND ((entity_type='recipe' AND payload->>'visibility'='public') OR (entity_type='food' AND payload->>'state'='reviewed') OR (entity_type='comment' AND payload->>'state'='public') OR (entity_type='votedRecipeIds' AND payload->>'enabled'='true')));
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cuki_runtime;
GRANT EXECUTE ON FUNCTION cuki_actor(),cuki_staff() TO cuki_runtime;
CREATE TABLE deleted_accounts(actor_id text PRIMARY KEY,deleted_at timestamptz NOT NULL);
