import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';import {readdir,readFile,rm,mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import sharp from 'sharp';
import {embedded,postgres,migrate,asActor,type Database,type Actor} from '../../packages/server/db';import {configuration} from '../../packages/server/config';import {createApp} from '../../apps/api/src/app';
import {initialState,reduceCommand,createSession} from '../../packages/core/state';import {uid,entryFromFood,stableJSON} from '../../packages/core/utils';import type {AppState,Command,Recipe,WorkoutPlan,OutboxOp} from '../../packages/core/types';
import {push,pull,saveEntity} from '../../packages/server/entities';import * as garden from '../../packages/server/garden';import {createJob,processOneAI,cancelJob,proposalAction,proposals,type AIProvider} from '../../packages/server/ai';import {entitlement,cacheSubscription,type Subscription,type BillingProvider,recordWebhook,reconcileBilling} from '../../packages/server/billing';import {quoteReward,reserveRedemption,processRedemption,reconcileRedemption,getRedemption} from '../../packages/server/rewards';
let db:Database,service:Awaited<ReturnType<typeof createApp>>,folder:string,clock=new Date('2026-09-15T12:00:00.000Z');const tokens=new Map<string,string>();
const fixtureAI:AIProvider={configured:true,async analyze(){return{explanation:'Estimación de prueba. Confirmar cantidades y aceites.',ingredients:[{name:'Pechuga',foodId:null,amount:150,unit:'g',note:'Aproximación'}]};}};
const fixtureBilling:BillingProvider={configured:false,async read(){throw Error('not configured')},async grant(){throw Error('not configured')}};
before(async()=>{folder=await mkdtemp(join(tmpdir(),'cuki-tests-'));db=process.env.DATABASE_URL?postgres(process.env.DATABASE_URL):await embedded();await migrate(db);const config=configuration({APP_ENV:'test',PUBLIC_ORIGIN:'http://127.0.0.1:3000',LOCAL_AUTH_SECRET:'test-only-auth-secret-01234567890123456789',MEDIA_SIGNING_SECRET:'test-only-media-secret-01234567890123456789',MEDIA_DIR:folder,REVENUECAT_WEBHOOK_AUTH:'test-only-webhook-authorization'});service=await createApp({db,config,now:()=>clock,ai:fixtureAI,billing:fixtureBilling});});
after(async()=>{await service?.app.close();await db?.close();await rm(folder,{force:true,recursive:true});const path='.local/mail';for(const name of await readdir(path).catch(()=>[])){const p=join(path,name);try{const v=JSON.parse(await readFile(p,'utf8'));if(String(v.to).endsWith('@tests.invalid'))await rm(p);}catch{}}});
async function user(role:Actor['role']='user',verified=true):Promise<Actor>{const id=uid(),email=id+'@tests.invalid';await db.query('INSERT INTO local_users(id,email,verified,role,created_at) VALUES($1,$2,$3,$4,now())',[id,email,verified,role]);const session=await db.transaction(tx=>service.auth.session(tx,{id,email,password_hash:null,verified,role,deleted_at:null}));tokens.set(id,session.access_token);return{id,email,verified,role};}
async function http(actor:Actor|null,path:string,method='GET',payload?:unknown,key=uid()){const res=await service.app.inject({method:method as any,url:path,headers:{...(actor?{authorization:'Bearer '+tokens.get(actor.id)}:{}),'idempotency-key':key,'content-type':'application/json'},...(payload===undefined?{}:{payload:JSON.stringify(payload)})});return{status:res.statusCode,body:res.json()};}
async function commands(actor:Actor,state:AppState,cmd:Command[],time=clock){let next=state;for(const c of cmd)next=reduceCommand(next,c,time.toISOString());const result=await push(db,actor,{operations:next.outbox},time);for(const r of result.results as any[])assert.equal(r.state,'accepted',JSON.stringify(r));return{...next,outbox:[]} as AppState;}
function op(entityType:string,entityId:string,payload:unknown,baseVersion=0,deleted=false):OutboxOp{return{id:uid(),entityType,entityId,payload,baseVersion,deleted,createdAt:clock.toISOString(),state:'pending'};}

test('migration is repeatable and current API serves original editorial data without fake community',async()=>{await migrate(db);const health=await http(null,'/health');assert.equal(health.status,200);const feed=await http(null,'/v1/recipes');assert.equal(feed.status,200);assert.equal(feed.body.items.length,8);assert.ok(feed.body.items.every((r:any)=>r.authorId==='cuki-editorial'&&r.upvotes===0));});
test('private endpoints require valid JWT; public catalog does not',async()=>{assert.equal((await http(null,'/v1/garden')).status,401);const a=await user();tokens.set(a.id,'invalid-token');assert.equal((await http(a,'/v1/sync/pull')).status,401);assert.equal((await http(null,'/v1/foods?q=arroz')).status,200);});
test('real SQLite-style commands synchronize with SQL receipts and reject changed idempotent body',async()=>{const a=await user();let s=initialState(a.id,'UTC',clock.toISOString());s=reduceCommand(s,{type:'profile',profile:{name:'Ana'}},clock.toISOString());const payload={operations:s.outbox};const one=await http(a,'/v1/sync/push','POST',payload);assert.equal(one.status,200);assert.equal(one.body.results[0].state,'accepted');assert.deepEqual((await http(a,'/v1/sync/push','POST',payload)).body,one.body);const modified=structuredClone(payload);(modified.operations[0].payload as any).name='Otra';assert.equal((await http(a,'/v1/sync/push','POST',modified)).body.results[0].state,'failed');const total=(await db.query('SELECT count(*) AS n FROM entities WHERE actor_id=$1',[a.id])).rows[0];assert.equal(Number(total.n),1);});
test('RLS isolates two users while public recipes stay visible',async()=>{const a=await user(),b=await user(),s=initialState(a.id,'UTC',clock.toISOString());const entry=entryFromFood(s.foods[0],100,'2026-09-15','lunch','UTC');await commands(a,s,[{type:'entry',entry}]);const read=await http(b,'/v1/sync/pull?cursor=0');assert.equal(read.body.changes.length,0);const denied=await asActor(db,b,tx=>tx.query('SELECT * FROM entities WHERE actor_id=$1',[a.id]));assert.equal(denied.rows.length,0);await assert.rejects(()=>asActor(db,b,tx=>tx.query("INSERT INTO entities(actor_id,entity_type,id,version,payload) VALUES($1,'profile','victim',1,'{}')",[a.id])));});
test('a stale mutation reports conflict; unrelated valid entries still commit',async()=>{const a=await user(),s=initialState(a.id,'UTC',clock.toISOString());const e=entryFromFood(s.foods[0],100,'2026-09-15','lunch','UTC');await commands(a,s,[{type:'entry',entry:e}]);const valid=entryFromFood(s.foods[1],120,'2026-09-15','dinner','UTC');const result=await push(db,a,{operations:[op('diary',e.id,e,0),op('diary',valid.id,valid)]},clock);assert.equal((result.results[0] as any).state,'conflict');assert.equal((result.results[1] as any).state,'accepted');});
test('nutritional totals and units cannot differ from the source snapshot',async()=>{const a=await user(),s=initialState(a.id,'UTC',clock.toISOString());const e=entryFromFood(s.foods[0],100,'2026-09-15','lunch','UTC');e.nutrition.energy=e.nutrition.energy!+10;const r=await push(db,a,{operations:[op('diary',e.id,e)]},clock);assert.equal((r.results[0] as any).state,'failed');e.nutrition.energy-=10;e.unit='ml';const bad=await push(db,a,{operations:[op('diary',e.id,e)]},clock);assert.equal((bad.results[0] as any).state,'failed');});
test('publication is moderated, upvotes are unique per actor and users cannot grant reviewed state',async()=>{const a=await user(),b=await user(),moderator=await user('moderator');let s=initialState(a.id,'UTC',clock.toISOString());const r:Recipe={...s.recipes[0],id:uid(),authorId:a.id,authorName:'Persona de prueba',visibility:'pending',createdAt:clock.toISOString()};s=await commands(a,s,[{type:'recipe',recipe:r}]);assert.equal((await http(b,'/v1/recipes/'+r.id)).status,404);assert.equal((await http(a,'/v1/admin/overview')).status,403);const row=(await db.query('SELECT * FROM moderation WHERE actor_id=$1',[a.id])).rows[0];const decision=await http(moderator,'/v1/admin/moderation/'+row.id,'POST',{decision:'approve',reason:'Contenido y procedencia revisados en prueba',version:1});assert.equal(decision.status,200,JSON.stringify(decision.body));assert.equal((await http(b,'/v1/recipes/'+r.id)).status,200);let bs=initialState(b.id,'UTC',clock.toISOString());bs=await commands(b,bs,[{type:'toggle',field:'votedRecipeIds',id:r.id}]);assert.equal((await http(b,'/v1/recipes/'+r.id)).body.upvotes,1);bs=await commands(b,bs,[{type:'toggle',field:'votedRecipeIds',id:r.id}]);assert.equal((await http(b,'/v1/recipes/'+r.id)).body.upvotes,0);const forged={...r,id:uid(),visibility:'public'};const denied=await push(db,a,{operations:[op('recipe',forged.id,forged)]},clock);assert.equal((denied.results[0] as any).state,'failed');});
test('native session wire records hydrate all independent sets and award one weekly credit',async()=>{const a=await user();let s=initialState(a.id,'UTC',clock.toISOString());const g=await garden.enroll(db,a,'UTC','garden-policy-2.0.0',uid(),clock);const session=createSession(s,undefined,0,[s.exercises[0].id],clock.toISOString());s=await commands(a,s,[{type:'startSession',session}]);const ex=s.sessions[0].exercises[0];const oneMinute=new Date(+clock+60000);s=await commands(a,s,[{type:'set',sessionId:session.id,exerciseId:ex.id,set:{...ex.sets[0],load:0,reps:12},complete:true}],oneMinute);s=await commands(a,s,[{type:'finishSession',id:session.id,note:''}],new Date(+clock+120000));const now=new Date(+clock+180000),state=await garden.getGarden(db,a,now);assert.equal(state!.creditedWeeks,1);await garden.getGarden(db,a,now);assert.equal((await garden.getGarden(db,a,now))!.creditedWeeks,1);assert.equal(state!.id,g.id);});
test('full 52-week ledger requires closure; concurrent harvests produce precisely one coin and archived plant',async()=>{const a=await user();const start=new Date('2025-01-01T12:00:00.000Z');const g=await garden.enroll(db,a,'America/New_York','garden-policy-2.0.0',uid(),start);for(let i=0;i<52;i++){const ended=new Date(Date.parse(g.boundaries[i])+3600000),sid=uid(),exid=uid();const sample=initialState(a.id,'UTC',ended.toISOString());const exercise=sample.exercises[0];const session={id:sid,version:1,name:'Sesión de constancia',planId:null,date:ended.toISOString().slice(0,10),timezone:'UTC',status:'completed',startedAt:new Date(+ended-600000).toISOString(),endedAt:ended.toISOString(),pausedAt:null,pausedSeconds:0,exercises:[{id:exid,exerciseId:exercise.id,sets:[],restSeconds:90,superset:null}],currentExercise:0,note:'',restDeadline:null,restNotificationId:null};await asActor(db,a,async tx=>{await saveEntity(tx,a.id,'session',sid,session,0,false,ended.toISOString());await saveEntity(tx,a.id,'set',uid(),{id:uid(),version:1,sessionId:sid,exerciseId:exid,kind:'working',loadMode:'bodyweight',load:null,reps:1,seconds:null,meters:null,rir:null,note:'',completedAt:ended.toISOString()},0,false,ended.toISOString());});const current=await garden.getGarden(db,a,ended);assert.equal(current!.creditedWeeks,i+1);}
 const before=new Date(Date.parse(g.endAt)-1);await assert.rejects(()=>garden.harvest(db,a,uid(),before));const result=await Promise.all(Array.from({length:8},()=>garden.harvest(db,a,uid(),new Date(g.endAt))));assert.equal(new Set(result.map(r=>r.coin.id)).size,1);assert.equal((await garden.collection(db,a)).length,1);assert.equal((await garden.wallet(db,a)).length,1);const next=await garden.enroll(db,a,'UTC','garden-policy-2.0.0',uid(),new Date(Date.parse(g.endAt)+1));assert.notEqual(next.id,g.id);assert.equal(next.creditedWeeks,0);});
test('private media strips EXIF, checks size, denies another actor and rejects forged tokens',async()=>{const a=await user(),b=await user();const data=await sharp({create:{width:64,height:64,channels:3,background:'#9a7442'}}).jpeg().withMetadata().toBuffer();const signed=await service.media.create(a,{purpose:'photo',mime:'image/jpeg',bytes:data.length},clock);const token=new URL(signed.url).searchParams.get('token')!;await assert.rejects(()=>service.media.put(signed.id,token,data.subarray(1),clock));await service.media.put(signed.id,token,data,clock);await service.media.complete(a,signed.id);await assert.rejects(()=>service.media.url(b,signed.id,clock));const url=await service.media.url(a,signed.id,clock),readToken=new URL(url).searchParams.get('token')!;const result=await service.media.get(signed.id,readToken,clock);assert.equal((await sharp(result.data).metadata()).exif,undefined);await assert.rejects(()=>service.media.get(signed.id,readToken+'x',clock));});
test('concurrent free AI reservations stop at five, with unique durable receipts',async()=>{const a=await user();const results=await Promise.allSettled(Array.from({length:15},()=>createJob(db,a,{route:'text',input:'Pollo con arroz',mediaId:null},uid(),fixtureAI,clock)));assert.equal(results.filter(r=>r.status==='fulfilled').length,5);const e=await entitlement(db,a,clock);assert.equal(e.captures.reserved,5);const first=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value;await cancelJob(db,a,first.id,clock);await cancelJob(db,a,first.id,clock);assert.equal((await entitlement(db,a,clock)).captures.reserved,4);});
test('AI worker validates its output and consumes quota only once; cancellation cannot be overwritten',async()=>{const a=await user();const j=await createJob(db,a,{route:'text',input:'Pollo',mediaId:null},uid(),fixtureAI,clock);for(let i=0;i<10;i++)await processOneAI(db,fixtureAI,service.media,clock);const read=(await http(a,'/v1/ai/jobs/'+j.id)).body;assert.equal(read.state,'review');assert.equal(read.ingredients[0].amount,150);const stat=await entitlement(db,a,clock);assert.equal(stat.captures.used,1);assert.equal(stat.captures.reserved,0);
 let release!:(v:unknown)=>void;const pending:AIProvider={configured:true,async analyze(){return new Promise(r=>release=r);}};const k=await createJob(db,a,{route:'text',input:'Arroz',mediaId:null},uid(),pending,clock);const running=processOneAI(db,pending,service.media,clock);for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,5));assert.ok(release);await cancelJob(db,a,k.id,clock);release({explanation:'Test',ingredients:[{name:'Arroz',foodId:null,amount:100,unit:'g',note:''}]});await running;assert.equal((await http(a,'/v1/ai/jobs/'+k.id)).body.state,'cancelled');assert.equal((await entitlement(db,a,clock)).captures.reserved,0);});
test('malformed AI output is retried then refunded, never accepted as successful analysis',async()=>{const a=await user(),bad:AIProvider={configured:true,async analyze(){return {error:'injected',ingredients:'not an array'};}};const j=await createJob(db,a,{route:'text',input:'Comida',mediaId:null},uid(),bad,clock);for(let i=0;i<4;i++)await processOneAI(db,bad,service.media,new Date(+clock+i*65000));assert.equal((await http(a,'/v1/ai/jobs/'+j.id)).body.state,'failed');assert.equal((await entitlement(db,a,clock)).captures.used,0);assert.equal((await entitlement(db,a,clock)).captures.reserved,0);});
test('proposals apply through version checks and revert without creating consumed meals',async()=>{const a=await user();const seed=initialState(a.id,'UTC',clock.toISOString());const planned={id:'new',version:1,date:'2026-09-15',meal:'lunch',recipeId:seed.recipes[0].id,recipe:seed.recipes[0],servings:1};const provider:AIProvider={configured:true,async analyze(){return{explanation:'Una propuesta revisable',changes:[{entityType:'plannedMeal',entityId:null,afterJSON:JSON.stringify(planned)}]};}};await createJob(db,a,{route:'next_meal',input:'Planificar almuerzo',mediaId:null},uid(),provider,clock);await processOneAI(db,provider,service.media,clock);const p=(await proposals(db,a))[0];assert.ok(p);assert.equal(p.state,'pending');await proposalAction(db,a,p.id,'accept',1,uid(),clock);const entries=(await pull(db,a,'0')).changes;assert.equal(entries.filter(e=>e.entityType==='plannedMeal').length,1);assert.equal(entries.filter(e=>e.entityType==='diary').length,0);await proposalAction(db,a,p.id,'revert',2,uid(),clock);assert.equal((await pull(db,a,'0')).changes.at(-1)!.deleted,true);});
test('unconfigured promotions preserve the free user coin and return no fictional success',async()=>{const a=await user();const challenge=uid();await db.query("INSERT INTO challenges(id,actor_id,state,timezone,policy_version,boundaries,seed,created_at) VALUES($1,$2,'harvested','UTC','garden-policy-2.0.0',$3::jsonb,1,$4)",[challenge,a.id,JSON.stringify(Array(53).fill(clock.toISOString())),clock.toISOString()]);const coin=uid();await db.query("INSERT INTO coins(id,actor_id,challenge_id,state,earned_at) VALUES($1,$2,$3,'available',$4)",[coin,a.id,challenge,clock.toISOString()]);const q=await quoteReward(db,a,coin,uid(),fixtureBilling,clock);assert.equal(q.eligible,false);assert.equal(q.route,null);await assert.rejects(()=>reserveRedemption(db,a,q.id,q.terms_hash,uid(),clock));assert.equal((await garden.wallet(db,a))[0].state,'available');});
test('real reward state machine is idempotent and holds a timeout reservation for reconciliation',async()=>{const a=await user();const challenge=uid(),coin=uid();await db.query("INSERT INTO challenges(id,actor_id,state,timezone,policy_version,boundaries,seed,created_at) VALUES($1,$2,'harvested','UTC','garden-policy-2.0.0',$3::jsonb,1,$4)",[challenge,a.id,JSON.stringify(Array(53).fill(clock.toISOString())),clock.toISOString()]);await db.query("INSERT INTO coins(id,actor_id,challenge_id,state,earned_at) VALUES($1,$2,$3,'available',$4)",[coin,a.id,challenge,clock.toISOString()]);let record:Subscription={plan:'free',state:'active',store:null,startAt:null,endAt:null,verifiedAt:clock.toISOString()},grants=0;const provider:BillingProvider={configured:true,async read(){return record},async grant(actor,end){grants++;record={plan:'reward_plus',state:'active',store:'promotional',startAt:clock.toISOString(),endAt:end,verifiedAt:clock.toISOString()};throw new Error('connection lost after provider committed');}};const q=await quoteReward(db,a,coin,uid(),provider,clock);assert.equal(q.eligible,true);const rr=await Promise.all([reserveRedemption(db,a,q.id,q.terms_hash,uid(),clock),reserveRedemption(db,a,q.id,q.terms_hash,uid(),clock)]);assert.equal(rr[0].id,rr[1].id);await processRedemption(db,a,rr[0].id,provider,clock);assert.equal((await getRedemption(db,a,rr[0].id)).state,'unknown_reconciling');assert.equal((await garden.wallet(db,a))[0].state,'reserved');await reconcileRedemption(db,a,rr[0].id,provider,clock);assert.equal((await getRedemption(db,a,rr[0].id)).state,'confirmed');assert.equal((await garden.wallet(db,a))[0].state,'redeemed');assert.equal(grants,1);assert.equal((await entitlement(db,a,clock)).captures.limit,150);});
test('webhook authorization, duplicate suppression and authoritative reconciliation',async()=>{const a=await user(),event={event:{id:uid(),type:'RENEWAL',app_user_id:a.id}};await assert.rejects(()=>recordWebhook(db,service.auth.config,'wrong',event,clock));const accepted=await recordWebhook(db,service.auth.config,'test-only-webhook-authorization',event,clock);assert.equal(accepted.duplicate,false);assert.equal((await recordWebhook(db,service.auth.config,'test-only-webhook-authorization',event,clock)).duplicate,true);const provider:BillingProvider={configured:true,async read(){return{plan:'plus',state:'active',store:'play_store',startAt:clock.toISOString(),endAt:new Date(+clock+86400000).toISOString(),verifiedAt:clock.toISOString()};},async grant(){throw Error('not used')}};await reconcileBilling(db,provider,clock);assert.equal((await entitlement(db,a,clock)).plan,'plus');});
test('privacy export contains only the actor data and deletion removes storage plus authorization',async()=>{const a=await user(),b=await user();await commands(a,initialState(a.id,'UTC',clock.toISOString()),[{type:'profile',profile:{name:'Export owner'}}]);await commands(b,initialState(b.id,'UTC',clock.toISOString()),[{type:'profile',profile:{name:'Other private name'}}]);const job=await service.privacy.request(a,'export',uid(),clock);await service.privacy.processOne(clock);const list=await service.privacy.list(a,clock);assert.equal(list[0].state,'completed');const u=new URL(list[0].downloadUrl!),data=await service.privacy.download(job.id,a.id,u.searchParams.get('expires')!,u.searchParams.get('token')!,clock);assert.ok(data.toString().includes('Export owner'));assert.ok(!data.toString().includes('Other private name'));await service.privacy.request(a,'delete',uid(),clock);await service.privacy.processOne(clock);assert.equal((await http(a,'/v1/garden')).status,401);assert.equal((await db.query('SELECT id FROM entities WHERE actor_id=$1',[a.id])).rows.length,0);assert.ok((await db.query('SELECT id FROM entities WHERE actor_id=$1',[b.id])).rows.length>0);});
test('local authentication verifies email, rotates refresh tokens and refuses reused refresh',async()=>{const email=uid()+'@tests.invalid',password='correct-test-password-82716';const signup=await http(null,'/auth/v1/signup','POST',{email,password});assert.equal(signup.status,200);assert.equal((await http(null,'/auth/v1/token?grant_type=password','POST',{email,password})).status,401);let token='';for(const path of await readdir('.local/mail')){const m=JSON.parse(await readFile(join('.local/mail',path),'utf8'));if(m.to===email)token=m.token;}assert.ok(token);const verified=await http(null,'/auth/v1/verify','POST',{email,token,type:'email'});assert.equal(verified.status,200,JSON.stringify(verified.body));const refresh=verified.body.refresh_token;const result=await http(null,'/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:refresh});assert.equal(result.status,200);assert.notEqual(result.body.refresh_token,refresh);assert.equal((await http(null,'/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:refresh})).status,401);});

test('new plants freeze their renderer and full procedural descriptor at enrollment',async()=>{
 const a=await user();const g=await garden.enroll(db,a,'UTC','garden-policy-2.0.0',uid(),clock);
 const row=(await db.query('SELECT plant_descriptor FROM challenges WHERE id=$1',[g.id])).rows[0];
 assert.equal(row.plant_descriptor.rendererVersion,'1.2.0');
 assert.equal(row.plant_descriptor.seed,g.plant.seed);
 assert.ok(row.plant_descriptor.leaves.length>0);
 const before=stableJSON(row.plant_descriptor);
 await migrate(db);await garden.getGarden(db,a,clock);
 const again=(await db.query('SELECT plant_descriptor FROM challenges WHERE id=$1',[g.id])).rows[0];
 assert.equal(stableJSON(again.plant_descriptor),before);
 assert.equal((await garden.getGarden(db,a,clock))!.plant.rendererVersion,'1.2.0');
});
test('a migrated legacy cycle retains renderer 1.0 rather than silently changing its plant',async()=>{
 const a=await user();const g=await garden.enroll(db,a,'UTC','garden-policy-2.0.0',uid(),clock);
 // Simulate a row created before the nullable descriptor column was introduced.
 await db.query('UPDATE challenges SET plant_descriptor=NULL WHERE id=$1',[g.id]);
 await migrate(db);
 const legacy=await garden.getGarden(db,a,clock);
 assert.equal(legacy!.plant.rendererVersion,'1.0.0');
 assert.equal(legacy!.plant.seed,g.plant.seed);
 assert.equal((await db.query('SELECT plant_descriptor FROM challenges WHERE id=$1',[g.id])).rows[0].plant_descriptor,null);
});

/** Server fixtures mint only local test credits; they are not evidence of store fulfillment. */
async function testRewardWallet(){
 const actor=await user(),challenge=uid(),coin=uid();
 await db.query("INSERT INTO challenges(id,actor_id,state,timezone,policy_version,boundaries,seed,created_at) VALUES($1,$2,'harvested','UTC','garden-policy-2.0.0',$3::jsonb,1,$4)",[challenge,actor.id,JSON.stringify(Array(53).fill(clock.toISOString())),clock.toISOString()]);
 await db.query("INSERT INTO coins(id,actor_id,challenge_id,state,earned_at) VALUES($1,$2,$3,'available',$4)",[coin,actor.id,challenge,clock.toISOString()]);
 return {actor,coin};
}
test('a genuinely expired Plus subscription is eligible through the same rule at quote and execution',async()=>{
 const {actor,coin}=await testRewardWallet();let grants=0;
 let record:Subscription={plan:'plus',state:'expired',store:'app_store',startAt:'2026-01-01T00:00:00Z',endAt:'2026-02-01T00:00:00Z',verifiedAt:clock.toISOString()};
 const provider:BillingProvider={configured:true,async read(){return record},async grant(_id,endAt){grants++;return record={plan:'reward_plus',state:'active',store:'promotional',startAt:clock.toISOString(),endAt,verifiedAt:clock.toISOString(),autoRenew:false}}};
 const quote=await quoteReward(db,actor,coin,uid(),provider,clock);assert.equal(quote.eligible,true);
 const reserved=await reserveRedemption(db,actor,quote.id,quote.terms_hash,uid(),clock);
 await processRedemption(db,actor,reserved.id,provider,clock);
 assert.equal((await getRedemption(db,actor,reserved.id)).state,'confirmed');assert.equal(grants,1);
 assert.equal((await garden.wallet(db,actor))[0].state,'redeemed');
});
test('invalid, expired or stale provider replies cannot consume a reward coin',async()=>{
 for(const invalid of [{state:'expired'},{endAt:'not-a-date'},{startAt:'not-a-date'},{startAt:'2099-01-01T00:00:00Z'},{verifiedAt:'2020-01-01T00:00:00Z'},{autoRenew:true}]){
  const {actor,coin}=await testRewardWallet();let grants=0;
  let record:Subscription={plan:'free',state:'active',store:null,startAt:null,endAt:null,verifiedAt:clock.toISOString()};
  const provider:BillingProvider={configured:true,async read(){return record},async grant(_id,endAt){grants++;return record={plan:'reward_plus',state:'active',store:'promotional',startAt:clock.toISOString(),endAt,verifiedAt:clock.toISOString(),autoRenew:false,...invalid} as Subscription}};
  const quote=await quoteReward(db,actor,coin,uid(),provider,clock);
  const reserved=await reserveRedemption(db,actor,quote.id,quote.terms_hash,uid(),clock);
  await processRedemption(db,actor,reserved.id,provider,clock);
  await reconcileRedemption(db,actor,reserved.id,provider,clock);
  assert.equal((await getRedemption(db,actor,reserved.id)).state,'unknown_reconciling',JSON.stringify(invalid));
  assert.equal((await garden.wallet(db,actor))[0].state,'reserved');assert.equal(grants,1);
  assert.equal((await entitlement(db,actor,clock)).plan,'free');
 }
});
test('Google extension preserves cancellation and never claims a cancelled plan will renew',async()=>{
 const {actor,coin}=await testRewardWallet();let calls=0;
 let record:Subscription={plan:'plus',state:'active',store:'play_store',startAt:'2026-09-01T00:00:00Z',endAt:'2026-10-01T00:00:00Z',productId:'plus:monthly',autoRenew:false,verifiedAt:clock.toISOString()};
 const provider:BillingProvider={configured:true,async read(){return record},async grant(){throw Error('wrong route')},async defer(_id,productId,endAt){calls++;assert.equal(productId,record.productId);return record={...record,endAt}}};
 const q=await quoteReward(db,actor,coin,uid(),provider,clock);
 assert.equal(q.route,'google_play_defer');assert.equal(q.auto_renew_after,false);
 assert.match(q.billing_effect,/sin reactivar/);assert.equal(q.benefit_end_at,'2026-11-01T00:00:00.000Z');
 const r=await reserveRedemption(db,actor,q.id,q.terms_hash,uid(),clock);await processRedemption(db,actor,r.id,provider,clock);
 assert.equal((await getRedemption(db,actor,r.id)).state,'confirmed');assert.equal(calls,1);
});
test('a store response that silently reactivates renewal is not accepted as the quoted benefit',async()=>{
 const {actor,coin}=await testRewardWallet();
 let record:Subscription={plan:'plus',state:'active',store:'play_store',startAt:'2026-09-01T00:00:00Z',endAt:'2026-10-01T00:00:00Z',productId:'plus:monthly',autoRenew:false,verifiedAt:clock.toISOString()};
 const provider:BillingProvider={configured:true,async read(){return record},async grant(){throw Error('wrong route')},async defer(_id,_product,endAt){return record={...record,endAt,autoRenew:true}}};
 const q=await quoteReward(db,actor,coin,uid(),provider,clock);const r=await reserveRedemption(db,actor,q.id,q.terms_hash,uid(),clock);
 await processRedemption(db,actor,r.id,provider,clock);assert.equal((await getRedemption(db,actor,r.id)).state,'unknown_reconciling');
 assert.equal((await garden.wallet(db,actor))[0].state,'reserved');
});
