'use strict';
let access=null,kind='moderation',cursor=null,config=null;
const $=id=>document.getElementById(id),status=(text)=>{$('status').textContent=text||'';};
async function request(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(access?{Authorization:'Bearer '+access}:{}),...options.headers}});const data=await res.json();if(!res.ok)throw Error(data.message||data.error||'No se pudo completar la acción.');return data;}
async function run(button,fn){if(button)button.disabled=true;status('Procesando…');try{await fn();status('');}catch(e){status(e.message);}finally{if(button)button.disabled=false;}}
function action(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=()=>run(b,fn);return b;}
function draw(row){const a=document.createElement('article'),h=document.createElement('h2');h.textContent=(row.entity_type||row.route||row.kind||row.action||kind)+' · '+(row.state||row.id);a.append(h);const p=document.createElement('p');p.textContent=[row.id,row.created_at,row.reason,row.error].filter(Boolean).join(' · ');a.append(p);const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='Examinar datos';pre.textContent=JSON.stringify(row,null,2);details.append(summary,pre);a.append(details);const controls=document.createElement('div');controls.className='actions';
 if(kind==='moderation'&&row.state==='pending'){const reason=document.createElement('textarea');reason.placeholder='Motivo de revisión (obligatorio)';reason.setAttribute('aria-label','Motivo para '+row.id);a.append(reason);for(const [label,decision] of [['Aprobar','approve'],['Pedir cambios','needs_changes'],['Rechazar','reject']])controls.append(action(label,async()=>{if(reason.value.trim().length<3)throw Error('Escribí un motivo.');await request('/v1/admin/moderation/'+encodeURIComponent(row.id),{method:'POST',body:JSON.stringify({decision,reason:reason.value,version:row.version})});await load();}));}
 if(kind==='jobs'&&row.state==='failed')controls.append(action('Revisar y reintentar',async()=>{await request('/v1/admin/jobs/'+encodeURIComponent(row.id)+'/retry',{method:'POST',body:'{}'});await load();}));
 if(kind==='redemptions'&&['reserved','awaiting_provider','unknown_reconciling'].includes(row.state))controls.append(action('Reconciliar con proveedor',async()=>{await request('/v1/admin/redemptions/'+encodeURIComponent(row.id)+'/reconcile',{method:'POST',body:'{}'});await load();}));
 if(kind==='privacy'&&row.state==='failed')controls.append(action('Reintentar operación',async()=>{await request('/v1/admin/privacy/'+encodeURIComponent(row.id)+'/retry',{method:'POST',body:'{}'});await load();}));
 if(kind==='reports'&&row.state==='open')controls.append(action('Marcar revisado',async()=>{const reason=prompt('Motivo y resolución:');if(!reason)return;await request('/v1/admin/reports/'+encodeURIComponent(row.id)+'/resolve',{method:'POST',body:JSON.stringify({reason})});await load();}));a.append(controls);return a;}
async function load(more=false){const data=await request('/v1/admin/queue/'+kind+'?cursor='+(more?cursor||'':''));if(!more)$('items').replaceChildren();for(const row of data.items)$('items').append(draw(row));if(!data.items.length&&!more)$('items').textContent='No hay elementos en esta cola.';cursor=data.cursor;$('more').hidden=!cursor;for(const b of $('tabs').querySelectorAll('button'))b.setAttribute('aria-current',String(b.dataset.kind===kind));}
$('login').onsubmit=e=>{e.preventDefault();const b=e.target.querySelector('button');run(b,async()=>{config=await request('/v1/public/config');const fields=new FormData(e.target);const result=await request(config.authUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.authPublicKey},body:JSON.stringify({email:fields.get('email'),password:fields.get('password')})});access=result.access_token;e.target.reset();const overview=await request('/v1/admin/overview');$('stats').textContent=Object.entries(overview).map(([k,v])=>k+': '+v).join(' · ');$('signin').hidden=true;$('console').hidden=false;$('logout').hidden=false;await load();});};
$('tabs').onclick=e=>{if(e.target.dataset.kind){kind=e.target.dataset.kind;run(e.target,()=>load());}};$('refresh').onclick=e=>run(e.target,()=>load());$('more').onclick=e=>run(e.target,()=>load(true));$('logout').onclick=()=>{access=null;$('items').replaceChildren();$('console').hidden=true;$('signin').hidden=false;$('logout').hidden=true;status('Sesión de administración cerrada.');};
