import {invariant} from '../core/utils';
export const POLICY='garden-policy-2.0.0';export const LATE_MS=7*86400000;
interface Civil {year:number;month:number;day:number;hour:number;minute:number;second:number;ms:number}
function parts(date:Date,zone:string):Civil{const p=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const n=(t:string)=>Number(p.find(x=>x.type===t)!.value);return{year:n('year'),month:n('month'),day:n('day'),hour:n('hour'),minute:n('minute'),second:n('second'),ms:date.getUTCMilliseconds()}}
const naive=(p:Civil)=>Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second,p.ms);
function resolveCivil(p:Civil,zone:string):number {const wall=naive(p),offsets=new Set<number>();for(const h of [-48,-24,-12,0,12,24,48]){const instant=wall+h*3600000;offsets.add(naive(parts(new Date(instant),zone))-instant)}const candidates=[...offsets].map(off=>wall-off);const exact=candidates.filter(x=>naive(parts(new Date(x),zone))===wall).sort((a,b)=>a-b);if(exact.length)return exact[0];const forward=candidates.map(x=>({x,delta:naive(parts(new Date(x),zone))-wall})).filter(x=>x.delta>0).sort((a,b)=>a.delta-b.delta||a.x-b.x);invariant(forward.length,'No se pudo resolver el horario local.');return forward[0].x}
export function boundaries(startAt:string,timezone:string):string[]{const start=new Date(startAt);invariant(Number.isFinite(+start),'Inicio inválido.');const p=parts(start,timezone),wall=naive(p);return Array.from({length:53},(_,i)=>{if(i===0)return start.toISOString();const d=new Date(wall+i*7*86400000);return new Date(resolveCivil({year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate(),hour:p.hour,minute:p.minute,second:p.second,ms:p.ms},timezone)).toISOString()})}
export function windowFor(b:string[],endedAt:string,receivedAt:string):number {invariant(b.length===53,'Se requieren 53 fronteras.');const ended=Date.parse(endedAt),received=Date.parse(receivedAt);if(!Number.isFinite(ended)||!Number.isFinite(received)||ended>received+300000)return -1;for(let i=0;i<52;i++){if(ended>=Date.parse(b[i])&&ended<Date.parse(b[i+1]))return received<=Date.parse(b[i+1])+LATE_MS?i:-1}return -1}
export function evaluate(b:string[],credited:number[],now:string){invariant(b.length===53,'Calendario inválido.');const time=Date.parse(now);const set=new Set(credited.filter(i=>Number.isInteger(i)&&i>=0&&i<52));const windows=Array.from({length:52},(_,i)=>({index:i+1,start:b[i],end:b[i+1],state:set.has(i)?'credited':time<Date.parse(b[i])?'future':time<Date.parse(b[i+1])?'open':time<=Date.parse(b[i+1])+LATE_MS?'awaiting_sync':'missed'}));const interrupted=windows.some(w=>w.state==='missed');const ready=!interrupted&&set.size===52&&time>=Date.parse(b[52]);return{windows,creditedWeeks:set.size,state:ready?'ready_to_harvest':interrupted?'interrupted':'active'} as const}
export function addCalendarMonth(iso:string){const d=new Date(iso);invariant(Number.isFinite(+d),'Fecha inválida.');const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString()}
export function xorshift32(seed:number){let s=(seed>>>0)||0x9e3779b9;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296}}
export interface LeafDescriptor {id:string;birthWeek:number;angle:number;height:number;length:number;width:number;bend:number;azimuth:number;stemLength:number;colorVariant:number}
export interface PlantDescriptor {seed:number;species:'cuki-variegata';generatorVersion:'1.0.0';rendererVersion:'1.0.0';leaves:LeafDescriptor[];roots:{angle:number;phase:number;width:number}[]}
export function generatePlant(seed:number):PlantDescriptor{invariant(Number.isInteger(seed)&&seed>=0&&seed<=0xffffffff,'La semilla debe ser uint32.');const rand=xorshift32(seed);const leaves=Array.from({length:23},(_,i)=>({id:`leaf-${i}`,birthWeek:i===0?1:Math.min(52,2+Math.round(i*2.28)),angle:i*2.39996+(rand()-.5)*.65,height:.12+i*.031+rand()*.13,length:.48+rand()*.36+(i>13?.12:0),width:.15+rand()*.085,bend:.12+rand()*.17,azimuth:.25+rand()*.65,stemLength:.18+rand()*.37,colorVariant:rand()}));leaves[22].birthWeek=52;return{seed,species:'cuki-variegata',generatorVersion:'1.0.0',rendererVersion:'1.0.0',leaves,roots:Array.from({length:36},()=>({angle:rand()*Math.PI*2,phase:rand()*10,width:.0015+rand()*.0025}))}}
export function leafGrowth(leaf:LeafDescriptor,week:number){const t=Math.min(1,Math.max(0,(week-leaf.birthWeek+1)/3));return t*t*(3-2*t)}
