import type {AppState,Command,OutboxOp} from './types';import {clone,initialState,reduceCommand} from './state';import {invariant,stableJSON,uid} from './utils';
export type SqlValue=string|number|null;
export interface SQLConnection {exec(sql:string,params?:SqlValue[]):Promise<void>;all<T>(sql:string,params?:SqlValue[]):Promise<T[]>}
export interface SQLDriver extends SQLConnection {transaction<T>(fn:(tx:SQLConnection)=>Promise<T>):Promise<T>}
export interface SyncChange {entityType:string;entityId:string;version:number;deleted:boolean;payload:unknown}
const listByType:Record<string,keyof AppState>={food:'foods',recipe:'recipes',diary:'diary',goal:'goals',plan:'plans',exercise:'exercises',collection:'collections',comment:'comments',plannedMeal:'plannedMeals',pantry:'pantry',measurement:'measurements'};
export class ClientRepo {
 private value:AppState;private listeners=new Set<()=>void>();private tail:Promise<unknown>=Promise.resolve();
 constructor(readonly driver:SQLDriver,readonly accountId:string,readonly timezone:string){this.value=initialState(accountId,timezone)}
 getSnapshot=()=>this.value;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn)};
 private publish(s:AppState){this.value=s;this.listeners.forEach(fn=>fn())}
 private enqueue<T>(fn:()=>Promise<T>):Promise<T>{const p=this.tail.then(fn);this.tail=p.catch(()=>{});return p}
 async init(){await this.driver.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');await this.driver.exec('CREATE TABLE IF NOT EXISTS actor_state (actor TEXT PRIMARY KEY, schema_version INTEGER NOT NULL, payload TEXT NOT NULL)');await this.driver.exec('CREATE TABLE IF NOT EXISTS local_operations (actor TEXT NOT NULL, operation_id TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(actor, operation_id))');await this.driver.exec("INSERT OR IGNORE INTO schema_migrations(version, applied_at) VALUES (1,datetime('now'))");const rows=await this.driver.all<{payload:string}>('SELECT payload FROM actor_state WHERE actor=?',[this.accountId]);if(rows[0]){const state=JSON.parse(rows[0].payload) as AppState;invariant(state.schemaVersion===1&&state.accountId===this.accountId,'Formato de datos local no compatible. No se borró tu información.');this.publish(state)}else await this.driver.exec('INSERT INTO actor_state(actor,schema_version,payload) VALUES (?,?,?)',[this.accountId,1,JSON.stringify(this.value)]);return this}
 dispatch(command:Command){return this.dispatchMany([command])}
 dispatchMany(commands:Command[],operationId=uid(),now=new Date().toISOString()):Promise<void>{const body=stableJSON(commands);return this.enqueue(async()=>{let next:AppState|undefined;await this.driver.transaction(async tx=>{const receipt=await tx.all<{body:string}>('SELECT body FROM local_operations WHERE actor=? AND operation_id=?',[this.accountId,operationId]);if(receipt[0]){invariant(receipt[0].body===body,'La clave de operación ya fue usada con otros datos.');return}const rows=await tx.all<{payload:string}>('SELECT payload FROM actor_state WHERE actor=?',[this.accountId]);let state=rows[0]?JSON.parse(rows[0].payload) as AppState:clone(this.value);for(let i=0;i<commands.length;i++)state=reduceCommand(state,commands[i],now,commands.length===1?operationId:operationId+':'+i);await tx.exec('UPDATE actor_state SET payload=? WHERE actor=?',[JSON.stringify(state),this.accountId]);await tx.exec('INSERT INTO local_operations(actor,operation_id,body) VALUES (?,?,?)',[this.accountId,operationId,body]);next=state});if(next)this.publish(next)})}
 mutate(fn:(s:AppState)=>void):Promise<void>{return this.enqueue(async()=>{let result:AppState|undefined;await this.driver.transaction(async tx=>{const rows=await tx.all<{payload:string}>('SELECT payload FROM actor_state WHERE actor=?',[this.accountId]);const s=rows[0]?JSON.parse(rows[0].payload) as AppState:clone(this.value);fn(s);s.revision++;await tx.exec('UPDATE actor_state SET payload=? WHERE actor=?',[JSON.stringify(s),this.accountId]);result=s});if(result)this.publish(result)})}
 async requestKey(scope:string,body:unknown){const key=scope+':'+stableJSON(body);let id='';await this.mutate(s=>{id=s.requestKeys[key]??uid();s.requestKeys[key]=id});return id}
 async applyCloud(patch:Partial<Pick<AppState,'garden'|'plants'|'coins'|'quotes'|'redemptions'|'entitlement'|'jobs'|'proposals'>>){await this.mutate(s=>Object.assign(s,clone(patch)))}
 async acceptSync(results:{id:string;state:'accepted'|'conflict'|'failed';message?:string;remote?:unknown}[],changes:SyncChange[],cursor:string){await this.mutate(s=>{for(const result of results){const op=s.outbox.find(x=>x.id===result.id);if(!op)continue;if(result.state==='accepted')s.outbox=s.outbox.filter(x=>x.id!==op.id);else{op.state=result.state;op.error=result.message;op.remote=result.remote}}for(const c of changes){if(s.outbox.some(o=>o.entityType===c.entityType&&o.entityId===c.entityId))continue;mergeChange(s,c)}s.cursor=cursor;s.lastSyncAt=new Date().toISOString()})}
 async resolveConflict(id:string,keepLocal:boolean){await this.mutate(s=>{const op=s.outbox.find(o=>o.id===id);invariant(op&&op.state==='conflict','Conflicto no disponible.');const remote=op.remote as SyncChange|undefined;invariant(remote,'Falta la versión remota del conflicto.');s.outbox=s.outbox.filter(x=>x.id!==id);if(keepLocal){s.outbox.push({...op,id:uid(),baseVersion:remote.version,state:'pending',error:undefined,remote:undefined})}else mergeChange(s,remote)})}
 async mergeGuest(guest:AppState){invariant(this.accountId!=='guest','Elegí una cuenta.');await this.mutate(s=>{const marker='guest-merge:'+guest.localPlantSeed;if(s.requestKeys[marker])return;for(const key of Object.values(listByType)){const local=guest[key] as unknown as {id:string}[];const target=s[key] as unknown as {id:string}[];for(const item of local){if(!target.some(x=>x.id===item.id)){const copy=clone(item) as Record<string,unknown>;if('authorId'in copy)copy.authorId=this.accountId;if('ownerId'in copy)copy.ownerId=this.accountId;target.push(copy as {id:string})}}}for(const session of guest.sessions)if(!s.sessions.some(x=>x.id===session.id))s.sessions.push(clone(session));for(const op of guest.outbox){if(s.outbox.some(x=>x.id===op.id))continue;const value=clone(op);if(value.payload&&typeof value.payload==='object'){const p=value.payload as Record<string,unknown>;if('authorId'in p)p.authorId=this.accountId;if('ownerId'in p)p.ownerId=this.accountId;}s.outbox.push(value)}s.profile={...s.profile,...guest.profile};s.requestKeys[marker]=new Date().toISOString()})}
 async removeLocal(){await this.enqueue(async()=>{await this.driver.transaction(async tx=>{await tx.exec('DELETE FROM actor_state WHERE actor=?',[this.accountId]);await tx.exec('DELETE FROM local_operations WHERE actor=?',[this.accountId])});this.publish(initialState(this.accountId,this.timezone))})}
}
export function mergeChange(s:AppState,c:SyncChange){
 const p=clone(c.payload) as Record<string,unknown>;
 if(c.entityType==='profile'){s.profile={...s.profile,...p};return}
 if(c.entityType==='session'){const old=s.sessions.find(x=>x.id===c.entityId);if(c.deleted){s.sessions=s.sessions.filter(x=>x.id!==c.entityId);return}const next={...p,version:c.version} as unknown as AppState['sessions'][number];next.exercises=next.exercises.map(e=>({...e,sets:old?.exercises.find(x=>x.id===e.id)?.sets??[]}));const i=s.sessions.findIndex(x=>x.id===next.id);if(i<0)s.sessions.push(next);else s.sessions[i]={...old,...next};return}
 if(c.entityType==='set'){const session=s.sessions.find(x=>x.id===p.sessionId);const exercise=session?.exercises.find(x=>x.id===p.exerciseId);if(!exercise)return;if(c.deleted){exercise.sets=exercise.sets.filter(x=>x.id!==c.entityId);return}const set={...p,version:c.version} as unknown as AppState['sessions'][number]['exercises'][number]['sets'][number];const i=exercise.sets.findIndex(x=>x.id===c.entityId);if(i<0)exercise.sets.push(set);else exercise.sets[i]=set;return}
 if(['savedRecipeIds','votedRecipeIds','followedIds','blockedIds','shoppingChecks'].includes(c.entityType)){const key=c.entityType as 'savedRecipeIds';const a=s[key];s[key]=a.filter(id=>id!==c.entityId);if(!c.deleted&&p.enabled)s[key].push(c.entityId);return}
 const key=listByType[c.entityType];if(!key)return;const a=s[key] as unknown as {id:string;version?:number}[];const i=a.findIndex(x=>x.id===c.entityId);if(c.deleted){if(key==='diary'){if(i>=0)a[i]={...p,id:c.entityId,version:c.version} as {id:string}}else if(i>=0)a.splice(i,1);return}const item={...p,id:c.entityId,version:c.version} as {id:string};if(i<0)a.push(item);else a[i]=item;
}
