import {validateWorkoutSchedule} from './workout-calendar';
import {acceptsSetRevision} from './set-revisions';
import type {AppState,Command,Exercise,OutboxOp,SetEntry,SessionExercise,WorkoutPlan,WorkoutSession} from './types';
import catalog from './catalog.json';import editorialRecipes from './recipes.json';
import {uid,invariant,localDate,validDate,validateNutrients,validateEntry,setValid,recipeNutrition} from './utils';
import {exercises} from './training';
export const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
export function initialState(accountId='guest',timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',now=new Date().toISOString()):AppState{return {schemaVersion:1,syncVersions:{},accountId,revision:0,profile:{name:'',timezone,units:'metric',showCalories:true,hideGarden:false,reminders:false,theme:'dark',reduceMotion:false,reduceTransparency:false,onboarded:false,intention:'general',allergies:[],excluded:[],equipment:[],days:3,consentVersion:null},selectedDate:localDate(new Date(now),timezone),localPlantSeed:parseInt(uid().replace(/-/g,'').slice(0,8),16)>>>0,foods:clone(catalog) as AppState['foods'],recipes:clone(editorialRecipes) as AppState['recipes'],diary:[],goals:[],sessions:[],plans:[],exercises:clone(exercises),drafts:{},comments:[],collections:[],savedRecipeIds:[],votedRecipeIds:[],followedIds:[],blockedIds:[],cooking:null,cookedIds:[],plannedMeals:[],pantry:[],shoppingChecks:[],measurements:[],jobs:[],proposals:[],garden:null,plants:[],coins:[],quotes:[],redemptions:[],entitlement:{plan:'free',state:'active',verifiedAt:null,expiresAt:null,captures:{used:0,reserved:0,limit:0},actions:{used:0,reserved:0,limit:0},store:null},outbox:[],cursor:null,lastSyncAt:null,requestKeys:{}}}
export function blankSet(e:Exercise,load:number|null=null):SetEntry{return{id:uid(),version:0,kind:e.modality==='timed'?'timed':e.modality==='distance'?'distance':'working',loadMode:e.loadMode,load,reps:null,seconds:null,meters:null,rir:null,note:'',completedAt:null}}
export function createSession(state:AppState,plan?:WorkoutPlan,dayIndex=0,exerciseIds?:string[],startedAt=new Date().toISOString()):WorkoutSession{const planned=plan?.days[dayIndex];const ids=exerciseIds??planned?.exercises.map(e=>e.exerciseId)??[];invariant(ids.length>0,'Elegí al menos un ejercicio.');return{id:uid(),version:0,name:planned?.name??'Sesión libre',planId:plan?.id??null,planDayId:planned?.id??null,date:localDate(new Date(startedAt),state.profile.timezone),timezone:state.profile.timezone,status:'active',startedAt,endedAt:null,pausedAt:null,pausedSeconds:0,exercises:ids.map((id,i)=>{const e=state.exercises.find(e=>e.id===id);invariant(e,'Ejercicio no encontrado.');const p=planned?.exercises[i];return{id:uid(),exerciseId:id,restSeconds:p?.restSeconds??90,superset:p?.superset??null,sets:Array.from({length:p?.sets??1},()=>({...blankSet(e),load:p?.load??null,reps:e.modality==='strength'?p?.repsMin??null:null}))}}),currentExercise:0,note:'',restDeadline:null,restNotificationId:null}}
function put<T extends {id:string}>(a:T[],v:T){const i=a.findIndex(x=>x.id===v.id);if(i<0)a.push(v);else a[i]=v}
function finite(n:number|null,min=0,max=1e7){return n===null||Number.isFinite(n)&&n>=min&&n<=max}
function validateSet(s:SetEntry){invariant(finite(s.load)&&finite(s.reps,0,100000)&&finite(s.seconds,0,86400)&&finite(s.meters,0,1e7)&&finite(s.rir,0,10),'Valor de serie inválido.');invariant(s.reps===null||Number.isInteger(s.reps),'Las repeticiones deben ser enteras.');invariant(s.note.length<=3000,'La nota es demasiado larga.');}
export function reduceCommand(input:AppState,command:Command,now=new Date().toISOString(),opId=uid()):AppState{
 const s=clone(input); s.syncVersions??={}; const ms=Date.parse(now);invariant(Number.isFinite(ms),'Fecha de operación inválida.');
 let changes:{type:string;id:string;value:unknown;base:number;deleted?:boolean}[]=[];
 const change=(type:string,id:string,value:unknown,base=0,deleted=false)=>{const key=type+'/'+id;const expected=s.syncVersions[key]??(type==='profile'?0:base);s.syncVersions[key]=expected+1;changes.push({type,id,value,base:expected,deleted});};
 const session=(id:string)=>{const v=s.sessions.find(x=>x.id===id);invariant(v&&['active','paused'].includes(v.status),'La sesión no está activa.');return v};
 const sessionMeta=(v:WorkoutSession,base:number)=>change('session',v.id,{...v,exercises:v.exercises.map(e=>({...e,sets:[]}))},base);
 switch(command.type){
 case 'profile': {const v={...s.profile,...command.profile};invariant(v.name.trim().length<=80,'Nombre demasiado largo.');try{new Intl.DateTimeFormat('en',{timeZone:v.timezone}).format()}catch{throw new Error('Zona horaria inválida.')}invariant(Number.isInteger(v.days)&&v.days>=1&&v.days<=7,'Días inválidos.');s.profile=v;change('profile',s.accountId,v,input.revision);break}
 case 'date':invariant(validDate(command.date),'Fecha inválida.');s.selectedDate=command.date;break;
 case 'goal':{const g={...command.goal,updatedAt:now};invariant(validDate(g.effectiveFrom),'Fecha inválida.');for(const k of ['energy','protein','carbs','fat'] as const)invariant(finite(g[k],0,k==='energy'?20000:3000),'Meta inválida.');invariant(g.energy===null||g.energy>0,'La meta calórica debe ser positiva.');const old=s.goals.find(x=>x.id===g.id);invariant(!old||g.version===old.version+1,'La meta cambió.');put(s.goals,g);change('goal',g.id,g,old?.version??0);break}
 case 'food':{const f=clone(command.food);invariant(f.name.trim().length>=2&&f.name.length<=200,'Nombre de alimento inválido.');validateNutrients(f.nutrients);invariant(f.state==='private'||f.state==='pending','La revisión de alimentos solo la confirma el servidor.');invariant(!s.foods.some(x=>x.id===f.id&&x.state==='editorial'),'No se modifica una fuente editorial. Creá una versión privada.');const old=s.foods.find(x=>x.id===f.id);invariant(!old||f.version===old.version+1,'El alimento cambió.');f.ownerId=s.accountId;put(s.foods,f);change('food',f.id,f,old?.version??0);break}
 case 'recipe':{const r=clone(command.recipe);invariant(r.title.trim().length>=3&&r.title.length<=200,'Título inválido.');invariant(r.minutes>0&&r.minutes<=1440&&r.steps.length>0&&r.steps.every(x=>x.text.trim()),'Completá minutos y pasos.');invariant(r.visibility==='private'||r.visibility==='pending','La publicación se confirma en el servidor.');invariant(r.authorId===s.accountId,'Autor no autorizado.');r.ingredients=r.ingredients.map(i=>{const f=i.snapshot??s.foods.find(x=>x.id===i.foodId);invariant(f,'Falta un ingrediente.');return{...i,foodVersion:f.version,snapshot:clone(f)}});recipeNutrition(r,s.foods);const old=s.recipes.find(x=>x.id===r.id);invariant(!old||r.version===old.version+1,'La receta cambió.');r.updatedAt=now;put(s.recipes,r);change('recipe',r.id,r,old?.version??0);break}
 case 'entry':{const e=clone(command.entry);validateEntry(e);const old=s.diary.find(x=>x.id===e.id);invariant(!old||e.version===old.version+1,'El registro cambió; revisalo antes de guardar.');put(s.diary,e);change('diary',e.id,e,old?.version??0);break}
 case 'deleteEntry':case 'restoreEntry':{const e=s.diary.find(x=>x.id===command.id);invariant(e,'Registro no encontrado.');const base=e.version;e.version++;e.deletedAt=command.type==='deleteEntry'?now:null;change('diary',e.id,e,base,!!e.deletedAt);break}
 case 'toggle':{const a=s[command.field];const exists=a.includes(command.id);s[command.field]=exists?a.filter(x=>x!==command.id):[...a,command.id];change(command.field,command.id,{id:command.id,enabled:!exists},0,!(!exists));break}
 case 'collection':{invariant(command.collection.name.trim().length>0&&command.collection.name.length<=120,'Nombre inválido.');put(s.collections,command.collection);change('collection',command.collection.id,command.collection);break}
 case 'comment':{invariant(s.accountId!=='guest'&&command.comment.authorId===s.accountId,'Iniciá sesión para comentar.');invariant(command.comment.text.trim().length>0&&command.comment.text.length<=3000,'Comentario inválido.');put(s.comments,command.comment);change('comment',command.comment.id,command.comment);break}
 case 'deleteComment':{const c=s.comments.find(x=>x.id===command.id);invariant(c&&c.authorId===s.accountId,'Comentario no autorizado.');c.state='deleted';change('comment',c.id,c,0,true);break}
 case 'cooking':s.cooking=command.cooking;break;
 case 'cooked':s.cooking=null;if(!s.cookedIds.includes(command.recipeId))s.cookedIds.push(command.recipeId);break;
 case 'plan':{const p=clone(command.plan);const old=s.plans.find(x=>x.id===p.id);invariant(p.name.trim()&&p.days.length>0&&p.days.every(d=>d.name.trim()&&d.exercises.length>0),'El plan necesita nombre, días y ejercicios.');invariant(!old||p.version===old.version+1,'El plan cambió; revisalo.');for(const d of p.days)validateWorkoutSchedule(d.schedule);for(const d of p.days)for(const e of d.exercises)invariant(Number.isInteger(e.sets)&&e.sets>=1&&e.sets<=50&&e.repsMin>=1&&e.repsMax>=e.repsMin&&e.restSeconds>=0&&e.restSeconds<=3600&&finite(e.load),'Parámetros del ejercicio inválidos.');put(s.plans,p);change('plan',p.id,p,old?.version??0);break}
 case 'deletePlan':{const p=s.plans.find(x=>x.id===command.id);s.plans=s.plans.filter(x=>x.id!==command.id);if(p)change('plan',p.id,p,p.version,true);break}
 case 'exercise':{invariant(command.exercise.custom&&command.exercise.name.trim(),'Ejercicio propio inválido.');invariant(!s.exercises.some(e=>e.id===command.exercise.id&&!e.custom),'No se modifica la biblioteca original.');put(s.exercises,command.exercise);change('exercise',command.exercise.id,command.exercise);break}
 case 'startSession':{if(s.sessions.some(x=>x.id===command.session.id))break;invariant(!s.sessions.some(x=>['active','paused'].includes(x.status)),'Ya hay una sesión en curso.');const v=clone(command.session);invariant(v.exercises.length>0&&v.exercises.every(e=>s.exercises.some(x=>x.id===e.exerciseId)),'La sesión necesita ejercicios válidos.');invariant(Date.parse(v.startedAt)<=ms+300000,'Fecha de inicio futura.');v.version=1;put(s.sessions,v);sessionMeta(v,0);for(const e of v.exercises)for(const set of e.sets){set.version=1;change('set',set.id,{...set,sessionId:v.id,exerciseId:e.id},0)};break}
 case 'set':{const v=session(command.sessionId);const e=v.exercises.find(x=>x.id===command.exerciseId);invariant(e,'Ejercicio de sesión no encontrado.');const old=e.sets.find(x=>x.id===command.set.id);invariant(old||command.set.version===0&&!command.baseSet,'La serie fue eliminada mientras la editabas.');invariant(!old||acceptsSetRevision(old,command.set,command.baseSet),'La serie cambió en otra edición; recargala.');const set=clone(command.set);validateSet(set);if(command.complete){invariant(!old?.completedAt,'Esta serie ya estaba completada.');set.completedAt=now;invariant(setValid(set)||set.kind==='warmup'&&(set.reps??set.seconds??0)>0,'Indicá repeticiones, tiempo o distancia válidos.');v.restDeadline=ms+e.restSeconds*1000;}set.version=(old?.version??0)+1;put(e.sets,set);change('set',set.id,{...set,sessionId:v.id,exerciseId:e.id},old?.version??0);break}
 case 'deleteSet':{const v=session(command.sessionId);const e=v.exercises.find(x=>x.id===command.exerciseId);invariant(e,'Ejercicio no encontrado.');const set=e.sets.find(x=>x.id===command.setId);invariant(set,'Serie no encontrada.');e.sets=e.sets.filter(x=>x.id!==set.id);change('set',set.id,{sessionId:v.id,exerciseId:e.id,id:set.id},set.version,true);break}
 case 'sessionExercise':{const v=session(command.sessionId);const base=v.version;const e=clone(command.exercise);invariant(s.exercises.some(x=>x.id===e.exerciseId),'Ejercicio desconocido.');if(command.replaceId){const i=v.exercises.findIndex(x=>x.id===command.replaceId);invariant(i>=0&&!v.exercises[i].sets.some(x=>x.completedAt),'No se reemplaza un ejercicio con series realizadas.');for(const t of v.exercises[i].sets)change('set',t.id,{id:t.id,sessionId:v.id},t.version,true);v.exercises[i]=e;}else v.exercises.push(e);v.version++;sessionMeta(v,base);for(const t of e.sets){t.version=1;change('set',t.id,{...t,sessionId:v.id,exerciseId:e.id},0)};break}
 case 'sessionIndex':{const v=session(command.sessionId);invariant(command.index>=0&&command.index<v.exercises.length,'Ejercicio fuera de rango.');v.currentExercise=command.index;break}
 case 'sessionNote':{const v=session(command.id);const base=v.version;invariant(command.note.length<=5000,'Nota demasiado larga.');v.note=command.note;v.version++;sessionMeta(v,base);break}
 case 'pauseSession':{const v=session(command.id);if(v.status==='active'){v.status='paused';v.pausedAt=now;}break}
 case 'resumeSession':{const v=session(command.id);if(v.pausedAt)v.pausedSeconds+=Math.max(0,(ms-Date.parse(v.pausedAt))/1000);v.status='active';v.pausedAt=null;break}
 case 'finishSession':case 'discardSession':{const existing=s.sessions.find(x=>x.id===command.id);invariant(existing,'Sesión no encontrada.');if(existing.status==='completed'&&command.type==='finishSession')break;if(existing.status==='discarded'&&command.type==='discardSession')break;const v=session(command.id);if(command.type==='finishSession')invariant(v.exercises.some(e=>e.sets.some(x=>x.completedAt)),'La sesión no contiene ninguna serie o actividad realizada.');const base=v.version;if(v.pausedAt)v.pausedSeconds+=Math.max(0,(ms-Date.parse(v.pausedAt))/1000);v.pausedAt=null;v.status=command.type==='finishSession'?'completed':'discarded';v.endedAt=now;v.restDeadline=null;v.version++;if(command.type==='finishSession')v.note=command.note;sessionMeta(v,base);break}
 case 'rest':{const v=session(command.sessionId);invariant(command.deadline===null||Number.isFinite(command.deadline),'Descanso inválido.');v.restDeadline=command.deadline;break}
 case 'notification':{const v=s.sessions.find(x=>x.id===command.sessionId);if(v)v.restNotificationId=command.notificationId;break}
 case 'draft':invariant(command.key.length<250,'Clave inválida.');s.drafts[command.key]=clone(command.value);break;
 case 'dropDraft':delete s.drafts[command.key];break;
 case 'plannedMeal':{const m=command.meal;invariant(validDate(m.date)&&m.servings>0&&Number.isFinite(m.servings),'Comida planificada inválida.');const old=s.plannedMeals.find(x=>x.id===m.id);invariant(!old||m.version===old.version+1,'La planificación cambió.');put(s.plannedMeals,clone(m));change('plannedMeal',m.id,m,old?.version??0);break}
 case 'deletePlannedMeal':{const m=s.plannedMeals.find(x=>x.id===command.id);s.plannedMeals=s.plannedMeals.filter(x=>x.id!==command.id);if(m)change('plannedMeal',m.id,m,m.version,true);break}
 case 'pantry':{invariant(command.item.amount>=0&&Number.isFinite(command.item.amount),'Cantidad inválida.');put(s.pantry,command.item);change('pantry',command.item.id,command.item);break}
 case 'deletePantry':s.pantry=s.pantry.filter(x=>x.id!==command.id);change('pantry',command.id,{id:command.id},0,true);break;
 case 'measurement':{const m=command.measurement;invariant(validDate(m.date)&&m.value>0&&m.value<1000,'Medida inválida.');put(s.measurements,m);change('measurement',m.id,m);break}
 case 'deleteMeasurement':s.measurements=s.measurements.filter(x=>x.id!==command.id);change('measurement',command.id,{id:command.id},0,true);break;
 case 'job':put(s.jobs,command.job);break;
 case 'proposal':put(s.proposals,command.proposal);break;
 default:{const never:never=command;throw new Error('Comando desconocido '+String(never));}
 }
 s.revision=input.revision+1;
 changes.forEach((c,i)=>s.outbox.push({id:changes.length===1?opId:`${opId}:${i}`,entityType:c.type,entityId:c.id,baseVersion:c.base,payload:clone(c.value),deleted:!!c.deleted,createdAt:now,state:'pending'}));
 return s;
}
