import { createRemoteJWKSet, jwtVerify, SignJWT } from 'jose';
import { randomBytes, randomInt, scrypt, timingSafeEqual } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Config } from './config';
import type { Actor, Database, SQL } from './db';
import { id, need, sha256, HttpError, parseBody } from './common';
const derive=(password:string,salt:string)=>new Promise<Buffer>((resolve,reject)=>scrypt(password,salt,64,(error,key)=>error?reject(error):resolve(key)));
const emailSchema=z.string().email().max(250).transform(s=>s.trim().toLowerCase());
interface LocalUser {id:string;email:string;password_hash:string|null;verified:boolean;role:Actor['role'];deleted_at:string|null}
export class AuthService {
 readonly key:Uint8Array;readonly jwks:ReturnType<typeof createRemoteJWKSet>|null;
 constructor(readonly db:Database,readonly config:Config){this.key=new TextEncoder().encode(config.authKey);this.jwks=config.authMode==='supabase'?createRemoteJWKSet(new URL(config.authIssuer+'/.well-known/jwks.json')):null}
 async authenticate(request:FastifyRequest):Promise<Actor>{
  const header=request.headers.authorization;need(header?.startsWith('Bearer '),'Iniciá sesión para continuar.',401);const token=header!.slice(7);let data;
  try{data=(await jwtVerify(token,this.jwks??this.key,{issuer:this.config.authIssuer,audience:'authenticated',algorithms:this.jwks?['ES256','RS256']:['HS256']})).payload}catch{throw new HttpError(401,'La sesión no es válida o venció.');}
  need(data.sub,'Falta el identificador de cuenta.',401);
  if((await this.db.query('SELECT actor_id FROM deleted_accounts WHERE actor_id=$1',[data.sub])).rows.length)throw new HttpError(401,'La cuenta fue eliminada.');
  if(this.config.authMode==='local'){
   const row=(await this.db.query<LocalUser>(`SELECT u.* FROM local_users u JOIN local_sessions s ON s.actor_id=u.id WHERE s.id=$1 AND u.id=$2 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.deleted_at IS NULL`,[data.sid,data.sub])).rows[0];need(row,'La sesión fue cerrada.',401);return{id:row.id,email:row.email,verified:row.verified,role:this.config.adminIds.includes(row.id)?'admin':row.role};
  }
  const res=await fetch(this.config.supabaseUrl+'/auth/v1/user',{headers:{apikey:this.config.supabasePublicKey,Authorization:header!},signal:AbortSignal.timeout(8000)});
  need(res.ok,'No se pudo validar el estado de la cuenta.',401);const user=await res.json() as {id:string;email?:string;email_confirmed_at?:string};need(user.id===data.sub,'Cuenta no válida.',401);
  return{id:user.id,email:user.email,verified:!!user.email_confirmed_at,role:this.config.adminIds.includes(user.id)?'admin':'user'};
 }
 async optional(req:FastifyRequest):Promise<Actor>{return req.headers.authorization?this.authenticate(req):{id:'public',verified:false,role:'user'}}
 async session(tx:SQL,user:LocalUser){const refresh=randomBytes(48).toString('base64url'),sid=id(),expires=Math.floor(Date.now()/1000)+3600;await tx.query('INSERT INTO local_sessions(id,actor_id,token_hash,expires_at) VALUES($1,$2,$3,$4)',[sid,user.id,sha256(refresh),new Date(Date.now()+30*86400000).toISOString()]);const access=await new SignJWT({sid,email:user.email,role:'authenticated'}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuer(this.config.authIssuer).setAudience('authenticated').setIssuedAt().setExpirationTime(expires).sign(this.key);return{access_token:access,refresh_token:refresh,token_type:'bearer',expires_in:3600,expires_at:expires,user:{id:user.id,email:user.email,email_confirmed_at:user.verified?new Date().toISOString():null}}}
 async mail(tx:SQL,user:LocalUser,purpose:string){const token=String(randomInt(100000,1000000)),mid=id();await tx.query('UPDATE local_mail SET used_at=now() WHERE actor_id=$1 AND purpose=$2 AND used_at IS NULL',[user.id,purpose]);await tx.query('INSERT INTO local_mail(id,actor_id,token_hash,purpose,expires_at) VALUES($1,$2,$3,$4,$5)',[mid,user.id,sha256(this.config.authKey+':'+token),purpose,new Date(Date.now()+600000).toISOString()]);const dir=resolve('.local/mail');await mkdir(dir,{recursive:true,mode:0o700});await writeFile(join(dir,mid+'.json'),JSON.stringify({developmentOnly:true,to:user.email,token,purpose,expiresInMinutes:10},null,2),{mode:0o600});}
 routes(app:FastifyInstance){
  if(this.config.authMode!=='local')return;
  app.post('/auth/v1/signup',async req=>{const body=parseBody(z.object({email:emailSchema,password:z.string().min(10).max(256)}),req.body);await this.db.transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['auth:'+body.email]);let user=(await tx.query<LocalUser>('SELECT * FROM local_users WHERE email=$1',[body.email])).rows[0];if(!user){const salt=randomBytes(16).toString('hex');const password=(await derive(body.password,salt)).toString('hex');user={id:id(),email:body.email,password_hash:salt+':'+password,verified:false,role:'user',deleted_at:null};await tx.query('INSERT INTO local_users(id,email,password_hash,created_at) VALUES($1,$2,$3,now())',[user.id,user.email,user.password_hash]);await this.mail(tx,user,'email')}});return{confirmation_required:true}});
  app.post('/auth/v1/otp',async req=>{const body=parseBody(z.object({email:emailSchema,create_user:z.boolean().optional()}),req.body);await this.db.transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['auth:'+body.email]);let user=(await tx.query<LocalUser>('SELECT * FROM local_users WHERE email=$1',[body.email])).rows[0];if(!user&&body.create_user){user={id:id(),email:body.email,password_hash:null,verified:false,role:'user',deleted_at:null};await tx.query('INSERT INTO local_users(id,email,created_at) VALUES($1,$2,now())',[user.id,user.email]);}if(user&&!user.deleted_at)await this.mail(tx,user,'email')});return{sent:true,developmentMailbox:'.local/mail'}});
  app.post('/auth/v1/recover',async req=>{const body=parseBody(z.object({email:emailSchema}),req.body);await this.db.transaction(async tx=>{const u=(await tx.query<LocalUser>('SELECT * FROM local_users WHERE email=$1 AND deleted_at IS NULL',[body.email])).rows[0];if(u)await this.mail(tx,u,'recovery')});return{sent:true}});
  app.post('/auth/v1/verify',async req=>{const body=parseBody(z.object({email:emailSchema,token:z.string().regex(/^\d{6}$/),type:z.enum(['email','recovery']).default('email')}),req.body);
   // Invalid attempts must commit, so throttling cannot be rolled back by an error response.
   const result=await this.db.transaction(async tx=>{const u=(await tx.query<LocalUser>('SELECT * FROM local_users WHERE email=$1 AND deleted_at IS NULL',[body.email])).rows[0];if(!u)return null;const m=(await tx.query<{id:string;token_hash:string;attempts:number}>('SELECT * FROM local_mail WHERE actor_id=$1 AND purpose=$2 AND used_at IS NULL AND expires_at>now() ORDER BY expires_at DESC LIMIT 1 FOR UPDATE',[u.id,body.type])).rows[0];if(!m||m.attempts>=5)return null;await tx.query('UPDATE local_mail SET attempts=attempts+1 WHERE id=$1',[m.id]);if(m.token_hash!==sha256(this.config.authKey+':'+body.token))return null;await tx.query('UPDATE local_mail SET used_at=now() WHERE id=$1',[m.id]);await tx.query('UPDATE local_users SET verified=true WHERE id=$1',[u.id]);return this.session(tx,{...u,verified:true})});need(result,'Código inválido o vencido.',401);return result;
  });
  app.post('/auth/v1/token',async req=>{const grant=(req.query as {grant_type?:string}).grant_type;if(grant==='password'){const b=parseBody(z.object({email:emailSchema,password:z.string().max(256)}),req.body);const u=(await this.db.query<LocalUser>('SELECT * FROM local_users WHERE email=$1 AND deleted_at IS NULL',[b.email])).rows[0];const [salt,expected]=(u?.password_hash??'dummy:').split(':');const digest=await derive(b.password,salt);need(expected&&digest.length===Buffer.from(expected,'hex').length&&timingSafeEqual(digest,Buffer.from(expected,'hex'))&&u?.verified,'Credenciales inválidas o correo sin confirmar.',401);return this.db.transaction(tx=>this.session(tx,u));}
   need(grant==='refresh_token','Tipo de autenticación no válido.');const b=parseBody(z.object({refresh_token:z.string().min(30).max(500)}),req.body);return this.db.transaction(async tx=>{const rows=(await tx.query<LocalUser&{session_id:string}>(`SELECT u.*,s.id AS session_id FROM local_sessions s JOIN local_users u ON u.id=s.actor_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.deleted_at IS NULL FOR UPDATE OF s`,[sha256(b.refresh_token)])).rows;need(rows[0],'Renová tu sesión.',401);await tx.query('UPDATE local_sessions SET revoked_at=now() WHERE id=$1',[rows[0].session_id]);return this.session(tx,rows[0])});
  });
  app.post('/auth/v1/logout',async req=>{const actor=await this.authenticate(req);await this.db.query('UPDATE local_sessions SET revoked_at=now() WHERE actor_id=$1',[actor.id]);return{signedOut:true}});
  app.put('/auth/v1/user',async req=>{const actor=await this.authenticate(req);const {password}=parseBody(z.object({password:z.string().min(10).max(256)}),req.body);const salt=randomBytes(16).toString('hex');await this.db.query('UPDATE local_users SET password_hash=$1 WHERE id=$2',[salt+':'+(await derive(password,salt)).toString('hex'),actor.id]);return{id:actor.id,email:actor.email}});
 }
}
