import type { Config } from './config';
import { asActor, lockActor, type Actor, type Database, type SQL } from './db';
import { need, HttpError, sha256, secureEqual } from './common';
import type { Entitlement } from '../core/types';
export interface Subscription {plan:Entitlement['plan'];state:Entitlement['state'];store:Entitlement['store'];startAt:string|null;endAt:string|null;productId?:string;autoRenew?:boolean;verifiedAt:string;raw?:unknown}
export interface BillingProvider {configured:boolean;read(actorId:string,now?:Date):Promise<Subscription>;grant(actorId:string,endAt:string):Promise<Subscription>;defer?(actorId:string,productId:string,endAt:string):Promise<Subscription>}
export class RevenueCat implements BillingProvider {
 readonly configured:boolean;
 constructor(private config:Config,private fetcher:typeof fetch=fetch){this.configured=!!config.revenueCatKey;}
 private async request(path:string,method='GET',body?:unknown){need(this.configured,'Las compras no están configuradas.',503);const res=await this.fetcher('https://api.revenuecat.com/v1'+path,{method,headers:{Authorization:'Bearer '+this.config.revenueCatKey,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});if(!res.ok)throw new HttpError(res.status>=500?503:502,'No se pudo confirmar el estado con la tienda.');return res.json();}
 async read(actorId:string,now=new Date()){const value=await this.request('/subscribers/'+encodeURIComponent(actorId));return fromSubscriber(value,now);}
 async defer(actorId:string,productId:string,endAt:string){const value=await this.request('/subscribers/'+encodeURIComponent(actorId)+'/subscriptions/'+encodeURIComponent(productId.split(':')[0])+'/defer','POST',{expiry_time_ms:Date.parse(endAt)});return fromSubscriber(value,new Date());}
 async grant(actorId:string,endAt:string){const value=await this.request('/subscribers/'+encodeURIComponent(actorId)+'/entitlements/plus/promotional','POST',{end_time_ms:Date.parse(endAt)});return fromSubscriber(value,new Date());}
}
export function fromSubscriber(value:any,now=new Date()):Subscription{
 const sub=value?.subscriber;need(sub&&typeof sub==='object','El proveedor devolvió datos incompletos.',502);
 const ent=sub.entitlements?.plus;const purchase=ent?sub.subscriptions?.[ent.product_identifier]:null;const grace=purchase?.grace_period_expires_date&&Date.parse(purchase.grace_period_expires_date)>+now;
 const current=ent&&(!ent.expires_date||Date.parse(ent.expires_date)>+now||grace);
 if(!current)return {plan:'free',state:'active',store:null,startAt:null,endAt:null,verifiedAt:now.toISOString()};
 const promotional=ent.product_identifier==='rc_promo'||purchase?.store==='promotional'||!purchase&&String(ent.product_identifier).startsWith('rc_promo');
 const store=promotional?'promotional':purchase?.store==='app_store'?'app_store':purchase?.store==='play_store'?'play_store':null;
 need(store,'La tienda de esta suscripción no está soportada.',502);
 return {plan:promotional?'reward_plus':purchase.period_type==='trial'?'trial':'plus',state:grace?'grace':'active',store,startAt:ent.purchase_date??purchase?.purchase_date??null,endAt:grace&&Date.parse(purchase.grace_period_expires_date)>Date.parse(ent.expires_date??'')?purchase.grace_period_expires_date:ent.expires_date??null,productId:ent.product_identifier,autoRenew:promotional?false:!purchase?.unsubscribe_detected_at,verifiedAt:now.toISOString(),raw:{productId:ent.product_identifier}};
}
export async function cacheSubscription(db:Database,actor:Actor,s:Subscription,now=new Date()){
 return asActor(db,actor,async tx=>{await lockActor(tx,actor.id);await tx.query(`INSERT INTO billing(actor_id,plan,state,store,starts_at,expires_at,verified_at,event_at,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$7,$8::jsonb) ON CONFLICT(actor_id) DO UPDATE SET plan=excluded.plan,state=excluded.state,store=excluded.store,starts_at=excluded.starts_at,expires_at=excluded.expires_at,verified_at=excluded.verified_at,event_at=excluded.event_at,payload=excluded.payload WHERE billing.event_at<=excluded.event_at`,[actor.id,s.plan,s.state,s.store,s.startAt,s.endAt,now.toISOString(),JSON.stringify({productId:s.productId,autoRenew:s.autoRenew})]);});
}
/** A month is anchored to the original day; Jan 31 -> Feb 28 -> Mar 31, never drifting. */
export function quotaPeriod(startAt:string,now:Date){const start=new Date(startAt);need(Number.isFinite(+start)&&+start<=+now,'Período de servicio inválido.');let n=(now.getUTCFullYear()-start.getUTCFullYear())*12+now.getUTCMonth()-start.getUTCMonth();const at=(m:number)=>{const d=new Date(start);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+m);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(start.getUTCDate(),last));return d;};if(+at(n)>+now)n--;return at(n).toISOString();}
export async function accessIn(tx:SQL,actor:Actor,now:Date){const b=(await tx.query('SELECT * FROM billing WHERE actor_id=$1',[actor.id])).rows[0];const paid=b&&['active','grace'].includes(b.state)&&(!b.expires_at||+new Date(b.expires_at)>+now);const plan:Entitlement['plan']=paid?b.plan:'free';const period=plan==='free'?'lifetime':plan==='trial'?'trial:'+new Date(b.starts_at).toISOString():quotaPeriod(new Date(b.starts_at).toISOString(),now);return {plan,period,captures:plan==='free'?(actor.verified?5:0):plan==='trial'?20:150,actions:plan==='free'?(actor.verified?3:0):plan==='trial'?40:300,billing:paid?b:null};}
export async function entitlement(db:Database,actor:Actor,now=new Date()):Promise<Entitlement>{return asActor(db,actor,async tx=>{const a=await accessIn(tx,actor,now);const q=(await tx.query('SELECT * FROM quota WHERE actor_id=$1 AND period=$2',[actor.id,a.period])).rows;const stat=(kind:string,limit:number)=>{const x=q.find(r=>r.kind===kind);return{used:x?.used??0,reserved:x?.reserved??0,limit};};return{plan:a.plan,state:a.billing?.state??'active',verifiedAt:a.billing?new Date(a.billing.verified_at).toISOString():null,expiresAt:a.billing?.expires_at?new Date(a.billing.expires_at).toISOString():null,store:a.billing?.store??null,captures:stat('capture',a.captures),actions:stat('action',a.actions)};});}
export async function reserveQuota(tx:SQL,actor:Actor,kind:'capture'|'action'|'review',now:Date){
 const a=await accessIn(tx,actor,now);let period=a.period;let limit=kind==='capture'?a.captures:a.actions;
 if(kind==='review'){limit=a.plan==='free'?0:a.plan==='trial'?2:1;period=a.plan==='trial'?a.period:'review-week:'+Math.floor(+now/(7*86400000));}
 await tx.query('INSERT INTO quota(actor_id,period,kind) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[actor.id,period,kind]);const reserved=(await tx.query('UPDATE quota SET reserved=reserved+1 WHERE actor_id=$1 AND period=$2 AND kind=$3 AND used+reserved<$4 RETURNING kind',[actor.id,period,kind,limit])).rows;need(reserved.length,'No quedan usos en este período. El registro manual sigue disponible.',429);return period;
}
export async function settleQuota(tx:SQL,job:any,use:boolean){if(job.quota_state!=='reserved')return;await tx.query('UPDATE quota SET reserved=GREATEST(0,reserved-1),used=used+$4 WHERE actor_id=$1 AND period=$2 AND kind=$3',[job.actor_id,job.period,job.quota_kind,use?1:0]);await tx.query('UPDATE jobs SET quota_state=$1 WHERE id=$2',[use?'used':'refunded',job.id]);}
/** Webhooks are durable notices: reconciliation reads the authoritative subscriber state instead of replaying deltas out of order. */
export async function recordWebhook(db:Database,config:Config,authorization:string|undefined,body:any,now:Date){need(config.webhookKey&&secureEqual(authorization??'',config.webhookKey),'No autorizado.',401);const e=body?.event;need(e&&typeof e.id==='string'&&e.id.length<200&&typeof e.type==='string','Evento inválido.');const digest=sha256(JSON.stringify(body));return db.transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',['webhook:'+e.id]);const old=(await tx.query('SELECT digest FROM webhook_events WHERE id=$1',[e.id])).rows[0];if(old){need(old.digest===digest,'ID de evento reutilizado con otros datos.',409);return {received:true,duplicate:true};}await tx.query('INSERT INTO webhook_events(id,kind,digest,received_at) VALUES($1,$2,$3,$4)',[e.id,e.type,digest,now.toISOString()]);if(e.type!=='TEST'){const actors=new Set<string>([e.app_user_id,...(e.transferred_to??[]),...(e.transferred_from??[])].filter((x:unknown):x is string=>typeof x==='string'&&x.length>0&&x.length<200));for(const a of actors){await tx.query('INSERT INTO billing_refresh(actor_id,requested_at) VALUES($1,$2) ON CONFLICT(actor_id) DO UPDATE SET requested_at=excluded.requested_at',[a,now.toISOString()]);}}return {received:true,duplicate:false};});}
export async function reconcileBilling(db:Database,provider:BillingProvider,now=new Date()){if(!provider.configured)return false;const rows=(await db.query('SELECT actor_id,requested_at FROM billing_refresh ORDER BY requested_at LIMIT 5')).rows;for(const row of rows){if((await db.query('SELECT actor_id FROM deleted_accounts WHERE actor_id=$1',[row.actor_id])).rows.length){await db.query('DELETE FROM billing_refresh WHERE actor_id=$1',[row.actor_id]);continue;}const actor:Actor={id:row.actor_id,verified:true,role:'user'};try{const result=await provider.read(actor.id,now);await cacheSubscription(db,actor,result,now);await db.query('DELETE FROM billing_refresh WHERE actor_id=$1 AND requested_at=$2',[actor.id,row.requested_at]);}catch{/* Retain durable refresh on provider failure. */}}return rows.length>0;}
