import Fastify,{type FastifyInstance,type FastifyRequest} from 'fastify';
import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import type { Config } from '../../../packages/server/config';
import { asActor,lockActor,type Actor,type Database } from '../../../packages/server/db';
import { need,HttpError,parseBody,id,writeAudit } from '../../../packages/server/common';
import { AuthService } from '../../../packages/server/auth';
import { push,pull } from '../../../packages/server/entities';
import * as community from '../../../packages/server/community';
import * as garden from '../../../packages/server/garden';
import { RevenueCat,entitlement,cacheSubscription,recordWebhook,reserveQuota,type BillingProvider } from '../../../packages/server/billing';
import { quoteReward,reserveRedemption,getRedemption,reconcileRedemption } from '../../../packages/server/rewards';
import { StructuredAI,createJob,getJob,cancelJob,proposals,proposalAction,type AIProvider } from '../../../packages/server/ai';
import { MediaService } from '../../../packages/server/media';
import { PrivacyService } from '../../../packages/server/privacy';
interface Options{db:Database;config:Config;now?:()=>Date;ai?:AIProvider;billing?:BillingProvider}
const str=(x:unknown,max=200)=>parseBody(z.string().min(1).max(max),x);
export async function createApp({db,config,now=()=>new Date(),ai=new StructuredAI(config),billing=new RevenueCat(config)}:Options){
 const app=Fastify({logger:false,bodyLimit:1_500_000,requestTimeout:45000,connectionTimeout:10000,trustProxy:false});const auth=new AuthService(db,config),media=new MediaService(db,config),privacy=new PrivacyService(db,config,media);
 const buckets=new Map<string,{count:number;until:number}>();
 app.addHook('onRequest',async(req,reply)=>{const stamp=Date.now(),key=req.ip+':'+(req.url.startsWith('/auth/')?'auth':'api'),limit=req.url.startsWith('/auth/')?20:180;let bucket=buckets.get(key);if(!bucket||bucket.until<stamp){bucket={count:0,until:stamp+60000};buckets.set(key,bucket);}bucket.count++;if(buckets.size>10000)for(const [k,b] of buckets)if(b.until<stamp)buckets.delete(k);if(bucket.count>limit){reply.header('Retry-After',Math.ceil((bucket.until-stamp)/1000));throw new HttpError(429,'Demasiadas solicitudes. Esperá un momento.');}});
 app.addHook('onSend',async(req,reply,payload)=>{reply.header('X-Content-Type-Options','nosniff').header('Referrer-Policy','no-referrer').header('X-Frame-Options','DENY').header('Cache-Control','no-store');if(req.url.startsWith('/admin')){const supabase=config.authMode==='supabase'?new URL(config.supabaseUrl).origin:'';reply.header('Content-Security-Policy',`default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' ${supabase}; frame-ancestors 'none'; base-uri 'none'; form-action 'self'`);}return payload;});
 app.setErrorHandler((caught,req,reply)=>{const error=caught instanceof Error?caught:new Error('Unknown failure');const status=error instanceof HttpError?error.statusCode:error instanceof z.ZodError?400:(error as any).statusCode??500;reply.code(status>=400&&status<=599?status:500).send({message:status>=500?'No se pudo completar la operación. Conservamos tus datos para reintentar.':error instanceof z.ZodError?'Revisá los datos enviados.':error.message,requestId:req.id,...(config.env==='test'?{diagnostic:error.message}:{} )});});
 app.addContentTypeParser('application/octet-stream',{parseAs:'buffer',bodyLimit:12_000_000},(req,body,done)=>done(null,body));auth.routes(app);
 const actor=(req:FastifyRequest)=>auth.authenticate(req);const opt=(req:FastifyRequest)=>auth.optional(req);const parameter=(req:FastifyRequest,name='id')=>str((req.params as any)[name]);const requestKey=(req:FastifyRequest)=>{const k=req.headers['idempotency-key'];need(typeof k==='string'&&k.length>0&&k.length<=200,'Falta la clave de idempotencia.');return k;};const staff=async(req:FastifyRequest)=>{const a=await actor(req);need(a.role==='admin'||a.role==='moderator','Acceso de operación requerido.',403);return a;};
 app.get('/health',async()=>{await db.query('SELECT 1');return{status:'ok',service:'cuki-api',environment:config.env};});
 app.get('/v1/public/config',async()=>({authUrl:config.authMode==='local'?config.origin:config.supabaseUrl,authPublicKey:config.authMode==='local'?'local-development':config.supabasePublicKey,aiAvailable:ai.configured,billingAvailable:billing.configured}));
 app.post('/v1/sync/push',async req=>{const a=await actor(req);const result=await push(db,a,req.body,now());await garden.getGarden(db,a,now());return result;});
 app.get('/v1/sync/pull',async req=>pull(db,await actor(req),String((req.query as any).cursor??'0')));
 app.get('/v1/recipes',async req=>{const q=req.query as any;return community.recipeFeed(db,await opt(req),String(q.q??''),q.cursor,media,now());});
 app.get('/v1/recipes/:id',async req=>community.recipeDetail(db,await opt(req),parameter(req),media,now()));
 app.get('/v1/recipes/:id/comments',async req=>community.comments(db,await opt(req),parameter(req)));
 app.get('/v1/foods',async req=>community.foodSearch(db,await opt(req),String((req.query as any).q??'')));
 app.get('/v1/foods/search',async req=>community.foodSearch(db,await opt(req),String((req.query as any).q??'')));
 app.get('/v1/foods/:id/versions',async req=>community.foodVersions(db,await opt(req),parameter(req)));
 app.get('/v1/foods/:id',async req=>community.foodDetail(db,await opt(req),parameter(req)));
 app.get('/v1/foods/barcode/:code',async req=>{const f=await community.barcodeFood(db,await opt(req),parameter(req,'code'),String((req.query as any).market??'AR'));need(f,'No encontramos este producto. Podés crearlo de forma privada.',404);return f;});
 app.post('/v1/reports',async req=>community.report(db,await actor(req),req.body,now()));
 app.get('/v1/moderation/mine',async req=>{const a=await actor(req);return asActor(db,a,async tx=>(await tx.query('SELECT * FROM moderation WHERE actor_id=$1 ORDER BY created_at DESC LIMIT 100',[a.id])).rows);});
 app.post('/v1/moderation/:id/appeal',async req=>community.appeal(db,await actor(req),parameter(req),req.body,now()));
 app.post('/v1/media/upload',async req=>media.create(await actor(req),req.body,now()));
 app.put('/v1/media/blob/:id',{bodyLimit:12_000_000},async req=>{need(Buffer.isBuffer(req.body),'Formato de carga incorrecto.');return media.put(parameter(req),str((req.query as any).token,2000),req.body,now());});
 app.get('/v1/media/blob/:id',async(req,reply)=>{const result=await media.get(parameter(req),str((req.query as any).token,2000),now());reply.type(result.mime);return result.data;});
 app.post('/v1/media/:id/complete',async req=>media.complete(await actor(req),parameter(req)));
 app.post('/v1/ai/jobs',async req=>createJob(db,await actor(req),req.body,requestKey(req),ai,now()));
 app.get('/v1/ai/jobs/:id',async req=>getJob(db,await actor(req),parameter(req)));
 app.post('/v1/ai/jobs/:id/cancel',async req=>cancelJob(db,await actor(req),parameter(req),now()));
 app.get('/v1/proposals',async req=>proposals(db,await actor(req)));
 for(const action of ['accept','reject','revert'] as const)app.post('/v1/proposals/:id/'+action,async req=>proposalAction(db,await actor(req),parameter(req),action,parseBody(z.object({version:z.number().int().positive()}),req.body).version,requestKey(req),now()));
 app.get('/v1/garden',async req=>garden.getGarden(db,await actor(req),now()));
 app.post('/v1/garden/enroll',async req=>{const body=parseBody(z.object({timezone:z.string().min(1).max(100),policyVersion:z.string().max(100)}),req.body);return garden.enroll(db,await actor(req),body.timezone,body.policyVersion,requestKey(req),now());});
 app.post('/v1/garden/archive',async req=>garden.archiveGarden(db,await actor(req),requestKey(req),now()));
 app.post('/v1/garden/harvest',async req=>garden.harvest(db,await actor(req),requestKey(req),now()));
 app.get('/v1/garden/collection',async req=>garden.collection(db,await actor(req)));
 app.get('/v1/rewards/wallet',async req=>garden.wallet(db,await actor(req)));
 app.post('/v1/rewards/quote',async req=>quoteReward(db,await actor(req),parseBody(z.object({coinId:z.string().max(200)}),req.body).coinId,requestKey(req),billing,now()));
 app.post('/v1/rewards/redeem',async req=>{const b=parseBody(z.object({quoteId:z.string().max(200),termsHash:z.string().length(64)}),req.body);return reserveRedemption(db,await actor(req),b.quoteId,b.termsHash,requestKey(req),now());});
 app.get('/v1/rewards/redemptions/:id',async req=>getRedemption(db,await actor(req),parameter(req)));
 app.get('/v1/billing/entitlement',async req=>{const a=await actor(req);if(billing.configured){const value=await billing.read(a.id,now());await cacheSubscription(db,a,value,now());}return entitlement(db,a,now());});
 app.post('/v1/billing/webhook',async req=>recordWebhook(db,config,req.headers.authorization,req.body,now()));
 app.post('/v1/privacy/export',async req=>privacy.request(await actor(req),'export',requestKey(req),now()));
 app.get('/v1/privacy/exports',async req=>privacy.list(await actor(req),now()));
 app.delete('/v1/privacy/account',async req=>{const b=parseBody(z.object({confirmation:z.literal('ELIMINAR')}),req.body);return privacy.request(await actor(req),'delete',requestKey(req),now());});
 app.get('/v1/privacy/download/:id',async(req,reply)=>{const q=req.query as any;const bytes=await privacy.download(parameter(req),str(q.actor),str(q.expires),str(q.token,2000),now());reply.type('application/json').header('Content-Disposition','attachment; filename="cuki-export.json"');return bytes;});
 for(const [route,file,type] of [['/admin','index.html','text/html'],['/admin/','index.html','text/html'],['/admin/app.js','app.js','application/javascript'],['/admin/style.css','style.css','text/css']])app.get(route,async(req,reply)=>{reply.type(type);return readFile(new URL('../../admin/'+file,import.meta.url),'utf8');});
 app.get('/v1/admin/overview',async req=>{const a=await staff(req);return asActor(db,a,async tx=>{const r:Record<string,number>={};for(const [name,sql] of [['revisiones',"SELECT count(*) AS n FROM moderation WHERE state='pending'"],['reportes',"SELECT count(*) AS n FROM reports WHERE state='open'"],['IA',"SELECT count(*) AS n FROM jobs WHERE state IN ('queued','running','failed')"],['canjes',"SELECT count(*) AS n FROM redemptions WHERE state NOT IN ('confirmed','failed_released')"]])r[name]=Number((await tx.query(sql)).rows[0].n);return r;});});
 const queues:Record<string,string>={moderation:'moderation',reports:'reports',jobs:'jobs',redemptions:'redemptions',privacy:'privacy_jobs',audit:'audit'};
 app.get('/v1/admin/queue/:kind',async req=>{const a=await staff(req),kind=parameter(req,'kind'),table=queues[kind];need(table,'Cola inexistente.',404);const offset=Number((req.query as any).cursor||0);need(Number.isInteger(offset)&&offset>=0&&offset<=100000,'Cursor inválido.');return asActor(db,a,async tx=>{const rows=(await tx.query(`SELECT * FROM ${table} ORDER BY created_at DESC,id DESC LIMIT 51 OFFSET $1`,[offset])).rows;return{items:rows.slice(0,50),cursor:rows.length>50?String(offset+50):null};});});
 app.post('/v1/admin/moderation/:id',async req=>community.moderate(db,await staff(req),parameter(req),req.body,now()));
 app.post('/v1/admin/reports/:id/resolve',async req=>{const a=await staff(req),mid=parameter(req),b=parseBody(z.object({reason:z.string().min(3).max(3000)}),req.body);return asActor(db,a,async tx=>{const r=(await tx.query('SELECT * FROM reports WHERE id=$1 FOR UPDATE',[mid])).rows[0];need(r,'Reporte inexistente.',404);await tx.query("UPDATE reports SET state='resolved' WHERE id=$1",[mid]);await writeAudit(tx,r.actor_id,'report.resolve',mid,now().toISOString(),{reason:b.reason},a.id);return{resolved:true};});});
 app.post('/v1/admin/jobs/:id/retry',async req=>{const a=await staff(req);return asActor(db,a,async tx=>{const j=(await tx.query("SELECT * FROM jobs WHERE id=$1 AND state='failed' FOR UPDATE",[parameter(req)])).rows[0];need(j,'Trabajo no disponible para reintento.',409);await lockActor(tx,j.actor_id);need(ai.configured,'Proveedor no configurado.',503);const target:Actor={id:j.actor_id,role:'user',verified:true};const period=await reserveQuota(tx,target,j.quota_kind,now());await tx.query("UPDATE jobs SET state='queued',quota_state='reserved',period=$1,attempts=0,error=NULL,next_attempt_at=NULL WHERE id=$2",[period,j.id]);await writeAudit(tx,j.actor_id,'ai.retry',j.id,now().toISOString(),{},a.id);return{queued:true};});});
 app.post('/v1/admin/privacy/:id/retry',async req=>{const a=await staff(req);need(a.role==='admin','Se requiere administrador.',403);return asActor(db,a,async tx=>{const rows=(await tx.query("UPDATE privacy_jobs SET state='queued',error=NULL,attempts=0 WHERE id=$1 AND state='failed' RETURNING id",[parameter(req)])).rows;need(rows.length,'No hay una operación pendiente de reintento.',409);return{queued:true};});});
 app.post('/v1/admin/redemptions/:id/reconcile',async req=>{const a=await staff(req);need(a.role==='admin','Se requiere administrador.',403);const row=await asActor(db,a,async tx=>(await tx.query('SELECT actor_id FROM redemptions WHERE id=$1',[parameter(req)])).rows[0]);need(row,'Canje inexistente.',404);return reconcileRedemption(db,{id:row.actor_id,verified:true,role:'user'},parameter(req),billing,now());});
 await app.ready();return{app,auth,ai,billing,media,privacy};
}
