import { z } from 'zod';
export const key = z.string().min(1).max(200).regex(/^[\w.:-]+$/);
const finite = z.number().finite().nonnegative();
const nullable = finite.nullable();
const instant = z.string().datetime({ offset: true });
export const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s => !Number.isNaN(Date.parse(s+'T00:00:00Z')) && new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s);
export const nutrition = z.object({energy:nullable,protein:nullable,carbs:nullable,fat:nullable,fiber:nullable,sugar:nullable,sodium:nullable}).strict();
export const foodSchema = z.object({ id:key,version:z.number().int().positive(),name:z.string().trim().min(2).max(200),brand:z.string().max(200),basis:z.enum(['per_100g','per_100ml']),preparation:z.enum(['raw','cooked','as_sold']),nutrients:nutrition,source:z.string().max(300),sourceUrl:z.string().url().nullable(),license:z.string().max(200),market:z.string().max(30),gtin:z.string().max(30).nullable(),servings:z.array(z.object({name:z.string().max(100),amount:finite.positive(),unit:z.enum(['g','ml'])})).max(50),state:z.enum(['editorial','private','pending','reviewed','needs_changes','rejected']),ownerId:key.optional(),updatedAt:instant});
const food = foodSchema;
const ingredient = z.object({id:key,foodId:key,grams:finite.positive().max(100000),foodVersion:z.number().int().positive().optional(),snapshot:food.optional()});
export const recipeSchema = z.object({ id:key,version:z.number().int().positive(),title:z.string().trim().min(3).max(200),description:z.string().max(10000),authorId:key,authorName:z.string().max(100),visibility:z.enum(['editorial','private','pending','public','withdrawn']),minutes:finite.positive().max(1440),servings:finite.positive().max(10000),cookedYield:finite.positive().nullable(),photoUri:z.string().max(2000).nullable(),assetKey:z.string().nullable().optional(),assetIds:z.array(key).max(20).optional(),previousVersionId:key.optional(),tags:z.array(z.string().max(50)).max(30),ingredients:z.array(ingredient).min(1).max(100),steps:z.array(z.object({id:key,text:z.string().trim().min(1).max(10000),seconds:finite.max(86400).nullable()})).min(1).max(100),createdAt:instant,updatedAt:instant.optional(),upvotes:z.number().optional()});
export const setSchema = z.object({id:key,version:z.number().int().nonnegative(),kind:z.enum(['working','warmup','drop','timed','distance']),loadMode:z.enum(['external_total','external_per_side','bodyweight','assisted','time','distance']),load:nullable,reps:z.number().int().nonnegative().max(100000).nullable(),seconds:finite.max(86400).nullable(),meters:finite.max(1e7).nullable(),rir:finite.max(10).nullable(),note:z.string().max(3000),completedAt:instant.nullable(),sessionId:key.optional(),exerciseId:key.optional()});
const sessionExercise=z.object({id:key,exerciseId:key,sets:z.array(setSchema).max(200),restSeconds:finite.max(3600),superset:z.string().max(100).nullable()});
const dayExercise=z.object({id:key,exerciseId:key,sets:z.number().int().min(1).max(50),repsMin:finite.positive(),repsMax:finite.positive(),load:nullable,restSeconds:finite.max(3600),superset:z.string().max(100).nullable()}).refine(e=>e.repsMax>=e.repsMin);
const tz=z.string().max(100).refine(s=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return true}catch{return false}});
export const entitySchemas:Record<string,z.ZodType>={
 food,
 recipe:recipeSchema,
 diary:z.object({id:key,version:z.number().int().positive(),date,timezone:tz,meal:z.enum(['breakfast','lunch','snack','dinner']),name:z.string().max(200),foodId:key.optional(),recipeId:key.optional(),sourceVersion:z.number().int().positive(),amount:finite.positive(),unit:z.enum(['g','ml','serving']),basis:z.string().optional(),nutrition,snapshot:z.object({foods:z.array(food).min(1).max(100),recipe:recipeSchema.optional()}),createdAt:instant,deletedAt:instant.nullable()}),
 goal:z.object({id:key,version:z.number().int().positive(),effectiveFrom:date,updatedAt:instant.optional(),energy:finite.positive().max(20000).nullable(),protein:finite.max(3000).nullable(),carbs:finite.max(3000).nullable(),fat:finite.max(3000).nullable()}),
 profile:z.object({name:z.string().max(80),timezone:tz,units:z.enum(['metric','imperial']),showCalories:z.boolean(),hideGarden:z.boolean(),reminders:z.boolean(),theme:z.enum(['dark','light','system']),reduceMotion:z.boolean(),reduceTransparency:z.boolean(),onboarded:z.boolean(),intention:z.string().max(100),allergies:z.array(z.string().max(100)).max(100),excluded:z.array(z.string().max(100)).max(100),equipment:z.array(z.string().max(100)).max(100),days:z.number().int().min(1).max(7),consentVersion:z.string().max(100).nullable()}),
 session:z.object({id:key,version:z.number().int().positive(),name:z.string().max(200),planId:key.nullable(),date,timezone:tz,status:z.enum(['active','paused','completed','discarded']),startedAt:instant,endedAt:instant.nullable(),pausedAt:instant.nullable(),pausedSeconds:finite,exercises:z.array(sessionExercise).min(1).max(100),currentExercise:z.number().int().nonnegative(),note:z.string().max(5000),restDeadline:z.number().finite().nullable(),restNotificationId:z.string().nullable()}),
 set:setSchema.extend({sessionId:key,exerciseId:key}),
 plan:z.object({id:key,version:z.number().int().positive(),name:z.string().trim().min(1).max(200),weeks:z.number().int().min(1).max(104),deload:z.boolean(),days:z.array(z.object({id:key,name:z.string().trim().min(1).max(100),exercises:z.array(dayExercise).min(1).max(100)})).min(1).max(31),createdAt:instant}),
 exercise:z.object({id:key,name:z.string().trim().min(1).max(200),muscle:z.string().max(100),pattern:z.string().max(100),equipment:z.string().max(100),instructions:z.array(z.string().max(3000)).max(100),modality:z.enum(['strength','timed','distance']),loadMode:z.enum(['external_total','external_per_side','bodyweight','assisted','time','distance']),custom:z.literal(true),mediaUri:z.string().max(2000).nullable()}),
 collection:z.object({id:key,name:z.string().trim().min(1).max(120),recipeIds:z.array(key).max(5000)}),
 comment:z.object({id:key,recipeId:key,parentId:key.nullable(),authorId:key,authorName:z.string().max(100),text:z.string().trim().min(1).max(3000),createdAt:instant,state:z.enum(['pending','public','deleted'])}),
 plannedMeal:z.object({id:key,version:z.number().int().positive(),date,meal:z.enum(['breakfast','lunch','snack','dinner']),recipeId:key,recipe:recipeSchema,servings:finite.positive().max(10000)}),
 pantry:z.object({id:key,foodId:key,amount:finite.max(100000),unit:z.enum(['g','ml'])}),
 measurement:z.object({id:key,date,kind:z.enum(['weight','waist','hip','chest']),value:finite.positive().max(1000),unit:z.enum(['kg','cm']),provenance:z.object({provider:z.enum(['healthkit','health_connect']),source:z.string().min(1).max(500),externalId:z.string().min(1).max(500),importedAt:instant}).optional()})
};
for(const field of ['savedRecipeIds','votedRecipeIds','followedIds','blockedIds','shoppingChecks'])entitySchemas[field]=z.object({id:key,enabled:z.boolean()});
export const operation=z.object({id:key,entityType:z.string().refine(s=>Object.hasOwn(entitySchemas,s)),entityId:key,baseVersion:z.number().int().nonnegative(),payload:z.unknown(),deleted:z.boolean(),createdAt:instant,state:z.enum(['pending','conflict','failed']),error:z.string().optional(),remote:z.unknown().optional()});
export function rejectUnsafeKeys(value:unknown,depth=0):void{if(depth>32)throw new z.ZodError([{code:'custom',path:[],message:'Datos demasiado anidados.'}]);if(!value||typeof value!=='object')return;for(const [k,v] of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(k))throw new z.ZodError([{code:'custom',path:[k],message:'Clave de datos no admitida.'}]);rejectUnsafeKeys(v,depth+1)}}
